// ============================================================
// LaTeX Generator Engine v2 — AST Pipeline
// Uses AST builder + serializer instead of string concatenation.
// Pipeline: ThesisData → ASTBuilder → Serializer → .tex string
// ============================================================

import type { ThesisData, ThesisReference, ReferenceType } from './thesis-types';
import { generateLatexFromAST } from '@/core/ast-builder';
import { escapeBibTeXField } from '@/engine/escape';

/**
 * Generate complete LaTeX document from ThesisData using the AST pipeline.
 * Output is compilable on Overleaf without modifications.
 */
export function generateLatex(data: ThesisData): string {
  try {
    return generateLatexFromAST(data);
  } catch (err) {
    throw new Error(`LaTeX generation failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
  }
}

/**
 * Generate BibTeX cite key from reference.
 *
 * FIX(ZONE-3B): Strip non-alphanumeric chars (apostrophes, accents) that
 * caused BibTeX compilation errors.
 */
export function generateCiteKey(ref: ThesisReference, index: number): string {
  const sanitize = (s: string): string => s
    .toLowerCase()
    .normalize('NFD')                      // decompose accents: é → e + ´
    .replace(/[\u0300-\u036f]/g, '')       // strip accent marks
    .replace(/[^a-z0-9]/g, '');           // strip everything else

  let authorPart = 'unknown';
  if (ref.authors) {
    const firstAuthor = ref.authors.split(',')[0].trim();
    const parts = firstAuthor.split(/\s+/);
    authorPart = sanitize(parts[parts.length - 1] || firstAuthor);
  }
  const yearPart = sanitize(ref.year || '0000');
  let titlePart = '';
  if (ref.title) {
    const firstWord = ref.title.split(/\s+/)
      .find(w => w.length > 3) || ref.title.split(/\s+/)[0];
    titlePart = sanitize(firstWord).slice(0, 8);
  }
  return `${authorPart}${yearPart}${titlePart}${index}`;
}

/**
 * Generate just the BibTeX file content.
 */
export function generateBibtexFile(data: ThesisData): string {
  const safeTitle = (data.metadata.title || 'Untitled').replace(/%/g, '\\%');
  let content = `% Bibliography for: ${safeTitle}\n`;
  content += `% Generated by ThesisForge\n`;
  content += `% Date: ${new Date().toISOString().split('T')[0]}\n\n`;

  for (let i = 0; i < data.references.length; i++) {
    content += generateBibtexEntry(data.references[i], i) + '\n';
  }

  return content;
}

/**
 * FIX(P0): Generate a single BibTeX entry with proper escaping.
 *
 * Critical fixes:
 * - All field values are now escaped via escapeBibTeXField() to prevent
 *   broken .bib files when reference data contains {, }, \, &, %, #, etc.
 * - 'thesis' type now maps to 'phdthesis' or 'mastersthesis' based on school name.
 * - biblatex-only types (@online, @dataset, @software) fall back to @misc
 *   since ThesisForge uses natbib by default (not biblatex).
 * - URL/DOI fields are NOT escaped (they're verbatim in BibTeX).
 * - The header comment in generateBibtexFile() now escapes the title.
 */
function generateBibtexEntry(ref: ThesisReference, index: number): string {
  const key = generateCiteKey(ref, index);

  // FIX: Map 'thesis' to 'phdthesis' or 'mastersthesis' based on school context.
  // Standard BibTeX has no @thesis type — must be one of these two.
  let bibType: string;
  if (ref.type === 'thesis') {
    const school = (ref.school || '').toLowerCase();
    bibType = /master|m\\.s\\.c|m\\.sc|m\\.tech/i.test(school) ? 'mastersthesis' : 'phdthesis';
  } else {
    // FIX: @online, @dataset, @software are biblatex-only entry types.
    // Since ThesisForge uses natbib (not biblatex) by default, these must
    // fall back to @misc with a type field for compatibility.
    const typeMap: Record<string, string> = {
      article: 'article',
      book: 'book',
      inproceedings: 'inproceedings',
      techreport: 'techreport',
      online: 'misc',      // biblatex-only → @misc with type = {Online}
      dataset: 'misc',     // biblatex-only → @misc with type = {Dataset}
      software: 'misc',    // biblatex-only → @misc with type = {Software}
      misc: 'misc',
    };
    bibType = typeMap[ref.type || 'misc'] || 'misc';
  }

  const fields: string[] = [];
  // FIX: Only emit author when non-empty. Empty author = {} produces
  // a broken BibTeX entry (required field missing). Let BibTeX report
  // the error rather than silently accepting an empty value.
  if (ref.authors && ref.authors.trim()) {
    fields.push(`  author  = {${escapeBibTeXField(ref.authors)}}`);
  }
  if (ref.title && ref.title.trim()) {
    fields.push(`  title   = {${escapeBibTeXField(ref.title)}}`);
  }

  if (ref.journal) fields.push(`  journal = {${escapeBibTeXField(ref.journal, 'journal')}}`);
  if (ref.bookTitle) fields.push(`  booktitle = {${escapeBibTeXField(ref.bookTitle, 'booktitle')}}`);
  if (ref.publisher) fields.push(`  publisher = {${escapeBibTeXField(ref.publisher, 'publisher')}}`);
  if (ref.school) fields.push(`  school = {${escapeBibTeXField(ref.school, 'school')}}`);
  fields.push(`  year = {${escapeBibTeXField(ref.year || '', 'year')}}`);
  if (ref.volume) fields.push(`  volume = {${escapeBibTeXField(ref.volume, 'volume')}}`);
  if (ref.number) fields.push(`  number = {${escapeBibTeXField(ref.number, 'number')}}`);
  if (ref.pages) fields.push(`  pages = {${escapeBibTeXField(ref.pages, 'pages')}}`);
  if (ref.edition) fields.push(`  edition = {${escapeBibTeXField(ref.edition, 'edition')}}`);
  if (ref.address) fields.push(`  address = {${escapeBibTeXField(ref.address, 'address')}}`);
  // DOI: preserve the DOI value without escaping (it's an identifier, not text)
  if (ref.doi) fields.push(`  doi = {${escapeBibTeXField(ref.doi, 'doi')}}`);
  // URL: preserve verbatim — no escaping needed inside BibTeX URL fields
  if (ref.url) fields.push(`  url = {${escapeBibTeXField(ref.url, 'url')}}`);
  if (ref.accessed) fields.push(`  urldate = {${escapeBibTeXField(ref.accessed, 'urldate')}}`);
  if (ref.note) fields.push(`  note = {${escapeBibTeXField(ref.note, 'note')}}`);
  if (ref.howPublished) fields.push(`  howpublished = {${escapeBibTeXField(ref.howPublished, 'howpublished')}}`);

  // For biblatex-only types using @misc fallback, add type field for clarity
  if (ref.type === 'dataset') {
    fields.push(`  type = {Dataset}`);
  }
  if (ref.type === 'software') {
    fields.push(`  type = {Software}`);
  }
  if (ref.type === 'online') {
    fields.push(`  type = {Online}`);
  }

  return `@${bibType}{${key},\n${fields.join(',\n')}\n}`;
}
