// ============================================================
// LaTeX Generator Engine v2 — AST Pipeline
// Uses AST builder + serializer instead of string concatenation.
// Pipeline: ThesisData → ASTBuilder → Serializer → .tex string
// ============================================================

import type { ThesisData, ThesisType, ThesisReference, ReferenceType } from './thesis-types';
import { generateLatexFromAST } from '@/core/ast-builder';

/**
 * Generate complete LaTeX document from ThesisData using the AST pipeline.
 * Output is compilable on Overleaf without modifications.
 */
export function generateLatex(data: ThesisData): string {
  return generateLatexFromAST(data);
}

/**
 * Generate BibTeX cite key from reference.
 */
export function generateCiteKey(ref: ThesisReference, index: number): string {
  let authorPart = 'unknown';
  if (ref.authors) {
    const firstAuthor = ref.authors.split(',')[0].trim();
    const parts = firstAuthor.split(/\s+/);
    authorPart = (parts[parts.length - 1] || firstAuthor)
      .toLowerCase()
      .replace(/[^a-z]/g, '');
  }
  const yearPart = ref.year || '0000';
  let titlePart = '';
  if (ref.title) {
    titlePart = ref.title.split(/\s+/)[0].toLowerCase().replace(/[^a-z]/g, '').slice(0, 8);
  }
  return `${authorPart}${yearPart}${titlePart}${index}`;
}

/**
 * Generate just the BibTeX file content.
 */
export function generateBibtexFile(data: ThesisData): string {
  let content = `% Bibliography for: ${data.metadata.title}\n`;
  content += `% Generated by ThesisForge\n`;
  content += `% Date: ${new Date().toISOString().split('T')[0]}\n\n`;

  for (let i = 0; i < data.references.length; i++) {
    content += generateBibtexEntry(data.references[i], i) + '\n';
  }

  return content;
}

function generateBibtexEntry(ref: ThesisReference, index: number): string {
  const key = generateCiteKey(ref, index);
  const typeMap: Record<ReferenceType, string> = {
    article: 'article',
    book: 'book',
    inproceedings: 'inproceedings',
    techreport: 'techreport',
    thesis: 'phdthesis',
    online: 'online',
    misc: 'misc',
  };
  const bibType = typeMap[ref.type] || 'misc';

  const fields: string[] = [];
  fields.push(`  author  = {${ref.authors || ''}}`);
  fields.push(`  title   = {${ref.title || ''}}`);

  if (ref.journal) fields.push(`  journal = {${ref.journal}}`);
  if (ref.bookTitle) fields.push(`  booktitle = {${ref.bookTitle}}`);
  if (ref.publisher) fields.push(`  publisher = {${ref.publisher}}`);
  if (ref.school) fields.push(`  school = {${ref.school}}`);
  fields.push(`  year = {${ref.year || ''}}`);
  if (ref.volume) fields.push(`  volume = {${ref.volume}}`);
  if (ref.number) fields.push(`  number = {${ref.number}}`);
  if (ref.pages) fields.push(`  pages = {${ref.pages}}`);
  if (ref.edition) fields.push(`  edition = {${ref.edition}}`);
  if (ref.address) fields.push(`  address = {${ref.address}}`);
  if (ref.doi) fields.push(`  doi = {${ref.doi}}`);
  if (ref.url) fields.push(`  url = {${ref.url}}`);
  if (ref.accessed) fields.push(`  urldate = {${ref.accessed}}`);
  if (ref.note) fields.push(`  note = {${ref.note}}`);
  if (ref.howPublished) fields.push(`  howpublished = {${ref.howPublished}}`);

  return `@${bibType}{${key},\n${fields.join(',\n')}\n}`;
}
