// ============================================================
// ThesisForge Core — LaTeX AST Builder (Engine v3)
// Builds a DocumentNode tree from ThesisData + template schema.
// Pipeline: ThesisData → ASTBuilder → Serializer → .tex
//
// ENGINE RULES:
// 1. The AST is the law. No string concatenation.
// 2. Every output element is a node. The serializer is the only
//    place that produces LaTeX strings.
// 3. The escaper runs on every user-provided string.
// 4. Template specialization means templates are DIFFERENT.
// ============================================================

import type { ThesisData, ThesisType, ThesisChapter, ThesisReference } from '@/lib/thesis-types';
import { TEMPLATE_SCHEMAS } from '@/core/templates';
import { escapeLatexBody, escapeLatexMeta } from '@/engine/escape';
import { resolvePackages, buildPackageConfiguration, detectFigures, detectTables } from '@/engine/packages';
import {
  type ASTNode,
  type DocumentNode,
  type CommandNode,
  type EnvironmentNode,
  type TextNode,
  type CommentNode,
  type BlankLineNode,
  type PackageImportNode,
  document,
  comment,
  blankLine,
  text,
  command,
  environment,
  usepackage,
  docClass,
  macroDef,
  rawLaTeX,
  newPage,
  label,
} from '@/core/ast';
import { serialize, serializeDocument } from '@/core/serializer';

// ============================================================
// Constants
// ============================================================

const FIGURE_PLACEHOLDER_TOKEN = '[figure]';
const TABLE_PLACEHOLDER_TOKEN = '[table]';

// ============================================================
// Public API
// ============================================================

/**
 * Build a complete LaTeX AST from ThesisData.
 * This is the main entry point for the AST pipeline.
 */
export function buildAST(data: ThesisData): DocumentNode {
  const schema = TEMPLATE_SCHEMAS[data.type];
  if (!schema) {
    throw new Error(`Unknown template type: ${data.type}`);
  }

  const children: ASTNode[] = [];

  // 1. Header comment
  children.push(buildHeaderComment(data));

  // 2. Preamble (documentclass + packages + configuration + custom commands)
  children.push(...buildPreamble(data, schema));

  // 3. \begin{document}
  children.push(command('begin', ['document']));
  children.push(blankLine());

  // 4. Title page (template-specific)
  children.push(...buildTitlePage(data, schema));

  // 5. Front matter (dedication, declaration, abstract, ack, TOC, lists)
  children.push(...buildFrontMatter(data, schema));

  // 6. Main matter (chapters with labels and smart processing)
  children.push(...buildMainMatter(data, schema));

  // 7. Appendices
  if (data.appendices && data.appendices.length > 0) {
    children.push(...buildAppendices(data, schema));
  }

  // 8. Back matter (bibliography, glossary)
  children.push(...buildBackMatter(data, schema));

  // 9. \end{document}
  children.push(command('end', ['document']));

  return document(children);
}

/**
 * Generate LaTeX string from ThesisData using the AST pipeline.
 */
export function generateLatexFromAST(data: ThesisData): string {
  const ast = buildAST(data);
  return serializeDocument(ast);
}

// ============================================================
// Header Comment
// ============================================================

function buildHeaderComment(data: ThesisData): CommentNode {
  const title = data.metadata.title || 'Untitled Thesis';
  const date = new Date().toISOString().split('T')[0];
  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'PhD Dissertation',
    report: 'Research Report',
  };
  return comment(
    `============================================================\n` +
    `${title}\n` +
    `${typeLabels[data.type] || data.type}\n` +
    `Generated by ThesisForge\n` +
    `Date: ${date}\n` +
    `============================================================`
  );
}

// ============================================================
// Preamble Builder
// Uses the canonical package system from engine/packages.ts
// ============================================================

function buildPreamble(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];

  // Document class — merge user format options with schema defaults
  const classOptions = buildClassOptions(data, schema);
  nodes.push(docClass(schema.documentClass, classOptions));
  nodes.push(blankLine());

  // Packages — use the canonical package system
  const packages = resolvePackages(data);
  for (const pkg of packages) {
    nodes.push(usepackage(pkg.name, pkg.options));
  }
  nodes.push(blankLine());

  // Package configuration block — geometry, microtype, hyperref, fancyhdr, etc.
  // This is the single source of truth for all \setup{} commands
  const configBlock = buildPackageConfiguration(data);
  if (configBlock) {
    nodes.push(rawLaTeX(configBlock));
    nodes.push(blankLine());
  }

  return nodes;
}

function buildClassOptions(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): string[] {
  const options = [...schema.classOptions];

  // Apply user font size
  const fontSizeIdx = options.findIndex(o => ['10pt', '11pt', '12pt'].includes(o));
  if (fontSizeIdx >= 0) options[fontSizeIdx] = data.options.fontSize;

  // Apply user paper size
  const paperIdx = options.findIndex(o => ['a4paper', 'letterpaper'].includes(o));
  if (paperIdx >= 0) options[paperIdx] = data.options.paperSize;

  // Remove duplicates
  return [...new Set(options)];
}

// ============================================================
// Title Page Builder — Template-Specific
// Each template has a distinct, correct title page structure.
// A Bachelor title page and a PhD title page are not the same
// with different words. They are structurally different documents.
// ============================================================

function buildTitlePage(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const builders: Record<ThesisType, (data: ThesisData) => ASTNode[]> = {
    bachelor: buildBachelorTitlePage,
    master: buildMasterTitlePage,
    phd: buildPhDTitlePage,
    report: buildReportTitlePage,
  };

  const builder = builders[data.type] || buildBachelorTitlePage;
  return builder(data);
}

function buildBachelorTitlePage(data: ThesisData): ASTNode[] {
  const m = data.metadata;
  const nodes: ASTNode[] = [];

  nodes.push(comment('Title Page'));
  nodes.push(blankLine());

  const body: ASTNode[] = [
    rawLaTeX('\\centering'),
    rawLaTeX('\\vspace*{2cm}'),
    blankLine(),
  ];

  // University name
  if (m.university) {
    body.push(rawLaTeX(`{\\Large\\textbf{${escMeta(m.university)}}\\par}`));
    body.push(rawLaTeX('\\vspace{0.5cm}'));
  }
  // Department
  if (m.department) {
    body.push(rawLaTeX(`{\\large ${escMeta(m.department)}\\par}`));
    body.push(blankLine());
  }

  body.push(rawLaTeX('\\vspace{3cm}'));

  // Title
  body.push(rawLaTeX(`{\\Huge\\bfseries ${escMeta(m.title)}\\par}`));
  // Subtitle
  if (m.subtitle) {
    body.push(rawLaTeX('\\vspace{0.5cm}'));
    body.push(rawLaTeX(`{\\large\\itshape ${escMeta(m.subtitle)}\\par}`));
  }

  body.push(rawLaTeX('\\vspace{2cm}'));
  blankLine();

  // Author and Supervisor
  let authorBlock = '{\\large\n\\textbf{Author:} ' + escMeta(m.author);
  if (m.authorId) {
    authorBlock += ' (' + escMeta(m.authorId) + ')';
  }
  authorBlock += '\\par';
  if (m.supervisor) {
    authorBlock += '\\vspace{0.3cm}\n\\textbf{Supervisor:} ' + escMeta(m.supervisorTitle || 'Prof.') + ' ' + escMeta(m.supervisor) + '\\par';
  }
  authorBlock += '}';
  body.push(rawLaTeX(authorBlock));

  body.push(rawLaTeX('\\vfill'));

  // Degree and date
  const year = m.submissionDate
    ? new Date(m.submissionDate).getFullYear().toString()
    : new Date().getFullYear().toString();
  body.push(rawLaTeX(`{\\large Bachelor of Science\\par}`));
  body.push(rawLaTeX('\\vspace{0.3cm}'));
  body.push(rawLaTeX(`{\\large ${escMeta(m.location || '')} ${escMeta(year)}\\par}`));
  blankLine();

  nodes.push(environment('titlepage', body));
  nodes.push(blankLine());

  return nodes;
}

function buildMasterTitlePage(data: ThesisData): ASTNode[] {
  const m = data.metadata;
  const nodes: ASTNode[] = [];

  nodes.push(comment('Title Page'));
  nodes.push(blankLine());

  const body: ASTNode[] = [
    rawLaTeX('\\centering'),
    rawLaTeX('\\vspace*{1.5cm}'),
    blankLine(),
  ];

  // University with small caps
  if (m.university) {
    body.push(rawLaTeX(`{\\large\\textsc{${escMeta(m.university)}}\\par}`));
  }
  if (m.faculty) {
    body.push(rawLaTeX('\\vspace{0.3cm}'));
    body.push(rawLaTeX(`{\\normalsize ${escMeta(m.faculty)}\\par}`));
  }
  if (m.department) {
    body.push(rawLaTeX('\\vspace{0.3cm}'));
    body.push(rawLaTeX(`{\\normalsize ${escMeta(m.department)}\\par}`));
  }

  body.push(rawLaTeX('\\vspace{2cm}'));

  // Decorative rule above title
  body.push(rawLaTeX('\\hrule'));
  body.push(rawLaTeX('\\vspace{0.5cm}'));

  // Title
  body.push(rawLaTeX(`{\\LARGE\\bfseries ${escMeta(m.title)}\\par}`));

  // Subtitle
  if (m.subtitle) {
    body.push(rawLaTeX('\\vspace{0.3cm}'));
    body.push(rawLaTeX(`{\\large\\itshape ${escMeta(m.subtitle)}\\par}`));
  }

  // Decorative rule below title
  body.push(rawLaTeX('\\vspace{0.5cm}'));
  body.push(rawLaTeX('\\hrule'));

  body.push(rawLaTeX('\\vspace{2cm}'));
  blankLine();

  // Author info as tabular
  let infoRows = `\\textbf{Author:}     & ${escMeta(m.author)} \\\\[0.2cm]`;
  if (m.supervisor) {
    infoRows += `\n    \\textbf{Supervisor:} & ${escMeta(m.supervisorTitle || 'Prof.')} ${escMeta(m.supervisor)} \\\\[0.2cm]`;
  }
  if (m.coSupervisor) {
    infoRows += `\n    \\textbf{Co-supervisor:} & ${escMeta(m.coSupervisorTitle || 'Dr.')} ${escMeta(m.coSupervisor)} \\\\[0.2cm]`;
  }
  body.push(rawLaTeX(`\\begin{tabular}{rl}\n    ${infoRows}\n\\end{tabular}`));

  body.push(rawLaTeX('\\vfill'));

  // Degree and date
  const year = m.submissionDate
    ? new Date(m.submissionDate).getFullYear().toString()
    : new Date().getFullYear().toString();
  body.push(rawLaTeX(`{\\large ${escMeta(m.university || '')}\\par}`));
  body.push(rawLaTeX(`{\\large ${escMeta(year)}\\par}`));
  blankLine();

  nodes.push(environment('titlepage', body));
  nodes.push(blankLine());

  return nodes;
}

function buildPhDTitlePage(data: ThesisData): ASTNode[] {
  const m = data.metadata;
  const nodes: ASTNode[] = [];

  nodes.push(comment('Title Page'));
  nodes.push(blankLine());

  const body: ASTNode[] = [
    rawLaTeX('\\centering'),
    rawLaTeX('\\vspace*{1cm}'),
    blankLine(),
  ];

  // University with small caps
  if (m.university) {
    body.push(rawLaTeX(`{\\large\\textsc{${escMeta(m.university)}}\\par}`));
  }

  body.push(rawLaTeX('\\vspace{2cm}'));

  // Title — PhD title pages are more dramatic
  body.push(rawLaTeX(`{\\Huge\\bfseries\\setstretch{1.2}\n${escMeta(m.title)}\\par}`));

  if (m.subtitle) {
    body.push(rawLaTeX('\\vspace{0.5cm}'));
    body.push(rawLaTeX(`{\\Large\\itshape ${escMeta(m.subtitle)}\\par}`));
  }

  body.push(rawLaTeX('\\vspace{2cm}'));

  // Author
  body.push(rawLaTeX(`{\\Large ${escMeta(m.author)}\\par}`));

  body.push(rawLaTeX('\\vspace{3cm}'));
  blankLine();

  // PhD-specific declaration text
  body.push(rawLaTeX('{\\normalsize\nA thesis submitted in partial fulfilment of the requirements\\\\\nfor the degree of Doctor of Philosophy\\par}'));
  body.push(rawLaTeX('\\vspace{1cm}'));

  // Faculty and department
  let institutionLines = '';
  if (m.faculty) institutionLines += escMeta(m.faculty) + '\\\\[0.2cm]\n';
  if (m.department) institutionLines += escMeta(m.department) + '\\\\[0.2cm]\n';
  institutionLines += escMeta(m.university || '');
  body.push(rawLaTeX(`{\\normalsize\n${institutionLines}\\par}`));

  body.push(rawLaTeX('\\vfill'));

  // Supervisors
  if (m.supervisor) {
    body.push(rawLaTeX(`{\\normalsize\\textbf{Supervisor:} ${escMeta(m.supervisorTitle || 'Prof.')} ${escMeta(m.supervisor)}\\par}`));
  }
  if (m.coSupervisor) {
    body.push(rawLaTeX(`{\\normalsize\\textbf{Co-supervisor:} ${escMeta(m.coSupervisorTitle || 'Dr.')} ${escMeta(m.coSupervisor)}\\par}`));
  }
  body.push(blankLine());

  // Year
  const year = m.submissionDate
    ? new Date(m.submissionDate).getFullYear().toString()
    : new Date().getFullYear().toString();
  body.push(rawLaTeX(`{\\normalsize ${escMeta(year)}\\par}`));
  blankLine();

  nodes.push(environment('titlepage', body));
  nodes.push(blankLine());

  return nodes;
}

function buildReportTitlePage(data: ThesisData): ASTNode[] {
  const m = data.metadata;
  const nodes: ASTNode[] = [];

  nodes.push(comment('Title Page'));
  nodes.push(blankLine());

  const body: ASTNode[] = [
    rawLaTeX('\\centering'),
    rawLaTeX('\\vspace*{2cm}'),
    blankLine(),
  ];

  // Title — clean and centered
  body.push(rawLaTeX(`{\\Huge\\bfseries ${escMeta(m.title)}\\par}`));

  if (m.subtitle) {
    body.push(rawLaTeX('\\vspace{0.5cm}'));
    body.push(rawLaTeX(`{\\large ${escMeta(m.subtitle)}\\par}`));
  }

  body.push(rawLaTeX('\\vspace{3cm}'));
  blankLine();

  // Author and affiliation
  body.push(rawLaTeX(`{\\large ${escMeta(m.author)}\\par}`));
  if (m.university) {
    body.push(rawLaTeX('\\vspace{0.3cm}'));
    body.push(rawLaTeX(`{\\normalsize ${escMeta(m.university)}\\par}`));
  }
  if (m.department) {
    body.push(rawLaTeX('\\vspace{0.3cm}'));
    body.push(rawLaTeX(`{\\normalsize ${escMeta(m.department)}\\par}`));
  }
  body.push(rawLaTeX('\\vfill'));

  // Date
  const year = m.submissionDate
    ? new Date(m.submissionDate).getFullYear().toString()
    : new Date().getFullYear().toString();
  body.push(rawLaTeX(`{\\normalsize ${escMeta(m.location || '')}, ${escMeta(year)}\\par}`));
  blankLine();

  nodes.push(environment('titlepage', body));
  nodes.push(blankLine());

  return nodes;
}

// ============================================================
// Front Matter Builder
// Conditional: only includes sections that have content.
// Declaration page for bachelor/master/phd. Dedication for master/phd.
// ============================================================

function buildFrontMatter(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const { metadata, abstract, keywords, options } = data;
  const isReport = schema.documentClass === 'article';

  // \frontmatter only in report/book class
  if (!isReport) {
    nodes.push(comment('Front Matter'));
    nodes.push(command('frontmatter'));
    nodes.push(blankLine());
  } else {
    nodes.push(comment('Front Matter'));
  }

  // Declaration page — bachelor, master, phd only (not report)
  if (!isReport) {
    nodes.push(...buildDeclarationPage(data));
  }

  // Dedication — only if enabled and content provided
  if (options.includeDedication && metadata.dedication && metadata.dedication.trim()) {
    nodes.push(comment('Dedication'));
    const dedChildren: ASTNode[] = [
      rawLaTeX('\\vspace*{\\fill}'),
      rawLaTeX('\\begin{center}'),
      rawLaTeX('\\large\\itshape'),
      text(escMeta(metadata.dedication)),
      rawLaTeX('\\end{center}'),
      rawLaTeX('\\vspace*{\\fill}'),
    ];
    nodes.push(environment('dedication', dedChildren));
    nodes.push(newPage('cleardoublepage'));
    nodes.push(blankLine());
  }

  // Abstract — always included (even if empty, it's required by most universities)
  nodes.push(comment('Abstract'));
  const absLabel = isReport ? 'section' : 'chapter';
  nodes.push(command(absLabel, ['Abstract'], undefined, true));
  nodes.push(command('addcontentsline', ['toc', absLabel, 'Abstract']));
  nodes.push(blankLine());
  if (abstract && abstract.trim()) {
    nodes.push(...processChapterBody(abstract));
  } else {
    nodes.push(comment('TODO: Write your abstract here. Aim for 150-350 words.'));
    nodes.push(text('TODO: Write your abstract here.'));
  }
  // Keywords
  if (keywords && keywords.length > 0) {
    nodes.push(blankLine());
    nodes.push(command('noindent'));
    nodes.push(command('textbf', ['Keywords: ']));
    nodes.push(text(keywords.map(k => escMeta(k)).join(', ')));
    nodes.push(blankLine());
  }
  nodes.push(blankLine());

  // Acknowledgments — only if enabled and content provided
  if (options.includeAcknowledgment && metadata.acknowledgment && metadata.acknowledgment.trim()) {
    nodes.push(comment('Acknowledgments'));
    const ackCmd = isReport ? 'section' : 'chapter';
    nodes.push(command(ackCmd, ['Acknowledgments'], undefined, true));
    nodes.push(command('addcontentsline', ['toc', ackCmd, 'Acknowledgments']));
    nodes.push(blankLine());
    nodes.push(...processChapterBody(metadata.acknowledgment));
    nodes.push(blankLine());
  }

  // Table of Contents
  nodes.push(comment('Table of Contents'));
  nodes.push(command('tableofcontents'));
  nodes.push(newPage('cleardoublepage'));
  nodes.push(blankLine());

  // List of Figures — conditional on detected figures
  if (detectFigures(data.chapters)) {
    nodes.push(command('listoffigures'));
    nodes.push(newPage('cleardoublepage'));
    nodes.push(blankLine());
  }

  // List of Tables — conditional on detected tables
  if (detectTables(data.chapters)) {
    nodes.push(command('listoftables'));
    nodes.push(newPage('cleardoublepage'));
    nodes.push(blankLine());
  }

  return nodes;
}

/**
 * Declaration page — standard academic integrity declaration.
 * Included for bachelor, master, phd (not report).
 */
function buildDeclarationPage(data: ThesisData): ASTNode[] {
  const nodes: ASTNode[] = [];
  const m = data.metadata;

  nodes.push(comment('Declaration'));
  const declCmd = 'chapter';
  nodes.push(command(declCmd, ['Declaration'], undefined, true));
  nodes.push(command('addcontentsline', ['toc', declCmd, 'Declaration']));
  nodes.push(blankLine());

  const declarationText =
    'I declare that this thesis is my original work and has not been submitted ' +
    'for any degree or examination at any other university. All sources of information ' +
    'used have been duly acknowledged. This thesis does not contain other persons\\textquotesingle{} ' +
    'data, pictures, graphs or other information, unless specifically acknowledged as being ' +
    'sourced from other researchers. Where written permission has been granted, the extent ' +
    'of such permission has been clearly indicated.';

  nodes.push(...processChapterBody(declarationText));

  nodes.push(blankLine());
  nodes.push(rawLaTeX('\\vspace{2cm}'));
  nodes.push(blankLine());

  // Signature line
  const year = m.submissionDate
    ? new Date(m.submissionDate).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  nodes.push(rawLaTeX(
    `\\noindent\\begin{tabular}{ll}\n` +
    `  \\textbf{Name:}      & ${escMeta(m.author)} \\\\\n` +
    `  \\textbf{Date:}       & ${escMeta(year)} \\\\\n` +
    `  \\textbf{Signature:}  & \\rule[0.5ex]{6cm}{0.5pt} \\\\\n` +
    `\\end{tabular}`
  ));

  nodes.push(newPage('cleardoublepage'));
  nodes.push(blankLine());

  return nodes;
}

// ============================================================
// Main Matter Builder — Chapters with Labels
// ============================================================

function buildMainMatter(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const isReport = schema.documentClass === 'article';

  // \mainmatter only in report/book class
  if (!isReport) {
    nodes.push(comment('Main Matter'));
    nodes.push(command('mainmatter'));
    nodes.push(blankLine());
  } else {
    nodes.push(comment('Main Matter'));
  }

  for (let i = 0; i < data.chapters.length; i++) {
    const chapter = data.chapters[i];
    nodes.push(...buildChapter(chapter, data.type, schema, i));
  }

  return nodes;
}

function buildChapter(
  chapter: ThesisChapter,
  type: ThesisType,
  schema: typeof TEMPLATE_SCHEMAS[string],
  index: number
): ASTNode[] {
  const nodes: ASTNode[] = [];
  const chCmd = schema.chapterCommand.replace('\\', ''); // 'chapter' or 'section'
  const secCmd = type === 'report' ? 'subsection' : 'section';
  const body = (chapter.content || '').trim();
  const coreCount = schema.bodyStructure.length;

  // Generate a consistent label for cross-references
  const chapterLabel = generateLabel('chapter', chapter.title, chapter.id);

  // Empty chapter handling
  if (!body) {
    const isCoreChapter = chapter.number <= coreCount;
    const hasNoSubSections = !chapter.subSections || chapter.subSections.length === 0;

    if (!isCoreChapter && hasNoSubSections) {
      return []; // Suppress optional empty chapters entirely
    }

    // Required empty chapter — include with TODO placeholder
    nodes.push(comment(`${chCmd === 'chapter' ? 'Chapter' : 'Section'} ${chapter.number}: ${chapter.title}`));
    nodes.push(command(chCmd, [escMeta(chapter.title)]));
    nodes.push(label(chapterLabel));
    nodes.push(blankLine());
    nodes.push(comment(`TODO: Add content for "${chapter.title}". This section requires substantial writing.`));
    nodes.push(text('TODO: Add content for this section.'));
    nodes.push(blankLine());
    return nodes;
  }

  // Chapter heading with label
  const chLabel = chCmd === 'chapter' ? 'Chapter' : 'Section';
  nodes.push(comment(`${chLabel} ${chapter.number}: ${chapter.title}`));
  nodes.push(command(chCmd, [escMeta(chapter.title)]));
  nodes.push(label(chapterLabel));
  nodes.push(blankLine());

  // Chapter body — processed through the content pipeline
  nodes.push(...processChapterBody(body));
  nodes.push(blankLine());

  // Subsections
  if (chapter.subSections && chapter.subSections.length > 0) {
    for (let si = 0; si < chapter.subSections.length; si++) {
      const sub = chapter.subSections[si];
      if (sub.title?.trim()) {
        const subLabel = generateLabel('section', sub.title, sub.id);
        nodes.push(command(secCmd, [escMeta(sub.title)]));
        nodes.push(label(subLabel));
        nodes.push(blankLine());
        if (sub.content && sub.content.trim()) {
          nodes.push(...processChapterBody(sub.content));
          nodes.push(blankLine());
        }
      }
    }
  }

  return nodes;
}

// ============================================================
// Appendices Builder
// ============================================================

function buildAppendices(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const chCmd = schema.chapterCommand.replace('\\', '');

  nodes.push(comment('Appendices'));
  nodes.push(command('appendix'));
  nodes.push(blankLine());

  for (const appendix of data.appendices) {
    const appLabel = generateLabel('appendix', appendix.title, appendix.id);
    nodes.push(command(chCmd, [escMeta(appendix.title)]));
    nodes.push(label(appLabel));
    nodes.push(blankLine());
    if (appendix.content && appendix.content.trim()) {
      nodes.push(...processChapterBody(appendix.content));
      nodes.push(blankLine());
    }
  }

  return nodes;
}

// ============================================================
// Back Matter Builder — Bibliography (and glossary for PhD)
// ============================================================

function buildBackMatter(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const isReport = schema.documentClass === 'article';

  // \backmatter only in report/book class
  if (!isReport) {
    nodes.push(comment('Back Matter'));
    nodes.push(command('backmatter'));
    nodes.push(blankLine());
  } else {
    nodes.push(comment('Back Matter'));
  }

  // Glossary — PhD only
  if (data.type === 'phd' && data.options.includeGlossary) {
    nodes.push(command('chapter', ['Glossary']));
    nodes.push(command('printglossaries'));
    nodes.push(blankLine());
  }

  // Bibliography
  if (data.references.length === 0) {
    nodes.push(comment('No references added yet. Add references in Step 4 to populate this section.'));
    nodes.push(blankLine());
    return nodes;
  }

  // Use thebibliography for zero-config compilability
  nodes.push(command('chapter', ['Bibliography'], undefined, true));
  nodes.push(command('addcontentsline', ['toc', 'chapter', 'Bibliography']));
  nodes.push(blankLine());

  nodes.push(command('begin', ['thebibliography', String(data.references.length)]));
  nodes.push(blankLine());

  // Track used keys for deduplication
  const usedKeys = new Set<string>();

  for (let i = 0; i < data.references.length; i++) {
    const ref = data.references[i];
    let key = generateCiteKey(ref, i);

    // Deduplicate keys
    let originalKey = key;
    let dedupIndex = 0;
    while (usedKeys.has(key)) {
      dedupIndex++;
      key = `${originalKey}${String.fromCharCode(97 + dedupIndex)}`; // a, b, c...
    }
    usedKeys.add(key);

    const entryText = formatBibItemInline(ref);
    nodes.push(text(`  \\bibitem{${key}} ${entryText}`, true));
    nodes.push(blankLine());
  }

  nodes.push(command('end', ['thebibliography']));
  nodes.push(blankLine());

  // Include BibTeX source as comment block for advanced users
  nodes.push(comment(
    'BibTeX Source (for BibTeX workflow)\n' +
    'To switch: uncomment \\bibliography{references} and remove thebibliography above'
  ));
  nodes.push(blankLine());

  for (let i = 0; i < data.references.length; i++) {
    const ref = data.references[i];
    const bibEntry = formatBibTeXEntry(ref, i);
    nodes.push(comment(bibEntry));
    nodes.push(blankLine());
  }

  return nodes;
}

// ============================================================
// Content Processing Pipeline
// Converts plain text to AST nodes with smart processing:
//   1. Normalize whitespace
//   2. Split into paragraphs
//   3. Handle [figure]/[table] placeholders
//   4. Convert ## headings to \section
//   5. Escape LaTeX special chars (smart — preserves existing commands)
// ============================================================

function processChapterBody(content: string): ASTNode[] {
  if (!content || !content.trim()) return [];

  const nodes: ASTNode[] = [];

  // 1. Normalize line endings
  const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

  // 2. Split into paragraphs (double newline separator)
  const paragraphs = normalized.split(/\n\s*\n/).filter(p => p.trim());

  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) continue;

    // 3. Check for ## markdown heading → \subsection
    const headingMatch = trimmed.match(/^#{1,3}\s+(.+)$/);
    if (headingMatch) {
      const headingTitle = headingMatch[1].trim();
      const headingLabel = generateLabel('section', headingTitle);
      nodes.push(command('subsection', [escMeta(headingTitle)]));
      nodes.push(label(headingLabel));
      nodes.push(blankLine());
      continue;
    }

    // 4. Handle figure/table placeholders and regular text
    const parts = splitPlaceholders(trimmed);
    for (const part of parts) {
      if (part.type === 'figure') {
        nodes.push(...buildFigurePlaceholder(part.caption || '', part.count || 0));
      } else if (part.type === 'table') {
        nodes.push(...buildTablePlaceholder(part.caption || '', part.count || 0));
      } else {
        // Regular text — process each line
        const lines = part.content.split('\n');
        for (let j = 0; j < lines.length; j++) {
          if (j > 0) {
            // Line break within paragraph
            nodes.push(text('\\\\', true));
          }
          const line = lines[j].trim();
          if (line) {
            // Smart escape — preserves existing LaTeX commands
            nodes.push(text(escapeLatexBody(line)));
          }
        }
        nodes.push(blankLine());
      }
    }
  }

  return nodes;
}

// ============================================================
// Placeholder Handlers
// ============================================================

interface ContentPart {
  type: 'text' | 'figure' | 'table';
  content: string;
  caption?: string;
  count?: number;
}

function splitPlaceholders(content: string): ContentPart[] {
  const parts: ContentPart[] = [];
  const figureRegex = /\[figure\](?::([^\]]*))?/g;
  const tableRegex = /\[table\](?::([^\]]*))?/g;

  const tokens: Array<{ pos: number; len: number; type: 'figure' | 'table'; caption: string }> = [];

  let match: RegExpExecArray | null;
  while ((match = figureRegex.exec(content)) !== null) {
    tokens.push({ pos: match.index, len: match[0].length, type: 'figure', caption: match[1] || '' });
  }
  while ((match = tableRegex.exec(content)) !== null) {
    tokens.push({ pos: match.index, len: match[0].length, type: 'table', caption: match[1] || '' });
  }

  if (tokens.length === 0) {
    return [{ type: 'text', content }];
  }

  tokens.sort((a, b) => a.pos - b.pos);

  let lastEnd = 0;
  let figCount = 0;
  let tabCount = 0;

  for (const token of tokens) {
    if (token.pos > lastEnd) {
      parts.push({ type: 'text', content: content.slice(lastEnd, token.pos) });
    }
    if (token.type === 'figure') {
      figCount++;
      parts.push({ type: 'figure', content: '', caption: token.caption, count: figCount });
    } else {
      tabCount++;
      parts.push({ type: 'table', content: '', caption: token.caption, count: tabCount });
    }
    lastEnd = token.pos + token.len;
  }

  if (lastEnd < content.length) {
    parts.push({ type: 'text', content: content.slice(lastEnd) });
  }

  return parts;
}

function buildFigurePlaceholder(caption: string, count: number): ASTNode[] {
  const cap = caption || 'Figure placeholder';
  const figLabel = `fig:placeholder${count > 0 ? '-' + count : ''}`;
  return [
    environment('figure', [
      blankLine(),
      command('centering'),
      command('includegraphics', ['figures/placeholder'], ['width=0.8\\textwidth']),
      command('caption', [escMeta(cap)]),
      command('label', [figLabel]),
      blankLine(),
    ], ['htbp']),
    blankLine(),
  ];
}

function buildTablePlaceholder(caption: string, count: number): ASTNode[] {
  const cap = caption || 'Table placeholder';
  const tabLabel = `tab:placeholder${count > 0 ? '-' + count : ''}`;
  return [
    environment('table', [
      blankLine(),
      command('centering'),
      command('caption', [escMeta(cap)]),
      command('label', [tabLabel]),
      blankLine(),
      comment('Replace with your table content'),
      text('\\begin{tabular}{lcc}', true),
      text('\\toprule', true),
      text('Header 1 & Header 2 & Header 3 \\\\', true),
      text('\\midrule', true),
      text('Data 1 & Data 2 & Data 3 \\\\', true),
      text('Data 4 & Data 5 & Data 6 \\\\', true),
      text('\\bottomrule', true),
      text('\\end{tabular}', true),
      blankLine(),
    ], ['htbp']),
    blankLine(),
  ];
}

// ============================================================
// Label Generation — Document Intelligence
// Every chapter, section, figure, table gets a consistent label
// so students can use \\cref{} without manual label management.
// ============================================================

function generateLabel(type: string, title: string, id: string | undefined = undefined): string {
  const prefix: Record<string, string> = {
    chapter: 'ch',
    section: 'sec',
    subsection: 'subsec',
    figure: 'fig',
    table: 'tab',
    equation: 'eq',
    appendix: 'app',
  };

  const p = prefix[type] || 'item';

  // Use ID if available (more stable than title-based slugs)
  if (id) {
    const slug = id
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .slice(0, 30);
    if (slug) return `${p}:${slug}`;
  }

  // Fallback: derive from title
  const slug = (title || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 30);

  return `${p}:${slug}`;
}

// ============================================================
// Bibliography Formatting Helpers
// ============================================================

function generateCiteKey(ref: ThesisReference, index: number): string {
  const sanitize = (s: string): string => s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');

  let authorPart = 'unknown';
  if (ref.authors) {
    const firstAuthor = ref.authors.split(',')[0].trim();
    const parts = firstAuthor.split(/\s+/);
    authorPart = sanitize(parts[parts.length - 1] || firstAuthor);
  }
  const yearPart = sanitize(ref.year || '0000');
  let titlePart = '';
  if (ref.title) {
    const firstWord = ref.title.split(/\s+/)
      .find(w => w.length > 3) || ref.title.split(/\s+/)[0];
    titlePart = sanitize(firstWord).slice(0, 8);
  }
  return `${authorPart}${yearPart}${titlePart}${index}`;
}

function formatBibItemInline(ref: ThesisReference): string {
  let entry = `${escMeta(ref.authors)}, `;

  switch (ref.type) {
    case 'book':
      entry += `\\textit{${escMeta(ref.title)}}`;
      if (ref.edition) entry += `, ${escMeta(ref.edition)} edition`;
      if (ref.publisher) entry += `, ${escMeta(ref.publisher)}`;
      if (ref.address) entry += `, ${escMeta(ref.address)}`;
      if (ref.year) entry += `, ${escMeta(ref.year)}`;
      entry += '.';
      break;
    case 'article':
      entry += `\\textit{${escMeta(ref.title)}}, `;
      if (ref.journal) entry += `${escMeta(ref.journal)}, `;
      if (ref.volume) entry += `vol.~${escMeta(ref.volume)}, `;
      if (ref.number) entry += `no.~${escMeta(ref.number)}, `;
      if (ref.pages) entry += `pp.~${escMeta(ref.pages)}, `;
      if (ref.year) entry += `${escMeta(ref.year)}`;
      entry += '.';
      break;
    case 'inproceedings':
      entry += `\\textit{${escMeta(ref.title)}}, `;
      if (ref.bookTitle) entry += `in \\textit{${escMeta(ref.bookTitle)}}, `;
      if (ref.pages) entry += `pp.~${escMeta(ref.pages)}, `;
      if (ref.year) entry += `${escMeta(ref.year)}`;
      entry += '.';
      break;
    case 'online':
      entry += `\\textit{${escMeta(ref.title)}}, `;
      if (ref.url) entry += `\\url{${ref.url}}, `;
      if (ref.accessed) entry += `accessed: ${escMeta(ref.accessed)}`;
      entry += '.';
      break;
    case 'thesis':
      entry += `\\textit{${escMeta(ref.title)}}, `;
      if (ref.school) entry += `${escMeta(ref.school)}, `;
      if (ref.year) entry += `${escMeta(ref.year)}`;
      entry += '.';
      break;
    case 'techreport':
      entry += `\\textit{${escMeta(ref.title)}}, `;
      if (ref.publisher) entry += `${escMeta(ref.publisher)}, `;
      if (ref.year) entry += `${escMeta(ref.year)}`;
      entry += '.';
      break;
    default:
      entry += `\\textit{${escMeta(ref.title)}}`;
      if (ref.year) entry += `, ${escMeta(ref.year)}`;
      entry += '.';
  }

  return entry;
}

function formatBibTeXEntry(ref: ThesisReference, index: number): string {
  const key = generateCiteKey(ref, index);
  const typeMap: Record<string, string> = {
    article: 'article',
    book: 'book',
    inproceedings: 'inproceedings',
    techreport: 'techreport',
    thesis: 'phdthesis',
    online: 'online',
    misc: 'misc',
  };
  const bibType = typeMap[ref.type] || 'misc';

  const fields: string[] = [];
  fields.push(`  author  = {${ref.authors || 'TODO: Add author'}}`);
  fields.push(`  title   = {${ref.title || 'TODO: Add title'}}`);

  if (ref.journal) fields.push(`  journal = {${ref.journal}}`);
  if (ref.bookTitle) fields.push(`  booktitle = {${ref.bookTitle}}`);
  if (ref.publisher) fields.push(`  publisher = {${ref.publisher}}`);
  if (ref.school) fields.push(`  school = {${ref.school}}`);
  if (ref.year) fields.push(`  year = {${ref.year}}`);
  if (ref.volume) fields.push(`  volume = {${ref.volume}}`);
  if (ref.number) fields.push(`  number = {${ref.number}}`);
  if (ref.pages) {
    // Normalize dashes to en-dashes for LaTeX
    const normalizedPages = ref.pages.replace(/\s*[-\u2013]\s*/g, '--');
    fields.push(`  pages = {${normalizedPages}}`);
  }
  if (ref.edition) fields.push(`  edition = {${ref.edition}}`);
  if (ref.address) fields.push(`  address = {${ref.address}}`);
  if (ref.doi) fields.push(`  doi = {${ref.doi}}`);
  if (ref.url) fields.push(`  url = {${ref.url}}`);
  if (ref.accessed) fields.push(`  urldate = {${ref.accessed}}`);
  if (ref.note) fields.push(`  note = {${ref.note}}`);
  if (ref.howPublished) fields.push(`  howpublished = {${ref.howPublished}}`);

  return `@${bibType}{${key},\n${fields.join(',\n')}\n}`;
}

// ============================================================
// Utility — Escape shorthands
// ============================================================

/** Escape for metadata fields (title, author, etc.) — simple, fast */
function escMeta(str: string): string {
  return escapeLatexMeta(str);
}

/** Escape for chapter body text — smart, preserves LaTeX commands */
function esc(str: string): string {
  return escapeLatexBody(str);
}
