// ============================================================
// ThesisForge Core — LaTeX AST Builder
// Builds a DocumentNode tree from ThesisData + template schema.
// This replaces string concatenation with a proper AST pipeline.
// Pipeline: ThesisData → ASTBuilder → ASTOptimizer → Serializer → .tex
// ============================================================

import type { ThesisData, ThesisType, ThesisChapter, ThesisReference } from '@/lib/thesis-types';
import { TEMPLATE_SCHEMAS } from '@/core/templates';
import { escapeLatex } from '@/utils/latex-escape';
import {
  type ASTNode,
  type DocumentNode,
  type CommandNode,
  type EnvironmentNode,
  type TextNode,
  type CommentNode,
  type BlankLineNode,
  type PackageImportNode,
  document,
  comment,
  blankLine,
  text,
  command,
  environment,
  usepackage,
  docClass,
  macroDef,
} from '@/core/ast';
import { serialize, serializeDocument } from '@/core/serializer';

// ============================================================
// Constants
// ============================================================

const FIGURE_PLACEHOLDER_TOKEN = '[figure]';
const TABLE_PLACEHOLDER_TOKEN = '[table]';

// ============================================================
// Public API
// ============================================================

/**
 * Build a complete LaTeX AST from ThesisData.
 * This is the main entry point for the AST pipeline.
 */
export function buildAST(data: ThesisData): DocumentNode {
  const schema = TEMPLATE_SCHEMAS[data.type];
  if (!schema) {
    throw new Error(`Unknown template type: ${data.type}`);
  }

  const children: ASTNode[] = [];

  // 1. Header comment
  children.push(buildHeaderComment(data));

  // 2. Preamble (documentclass + packages + hypersetup + commands)
  children.push(buildPreamble(data, schema));

  // 3. \begin{document}
  children.push(blankLine());

  // 4. Title page
  children.push(buildTitlePage(data, schema));

  // 5. Front matter
  children.push(buildFrontMatter(data, schema));

  // 6. Main matter (chapters)
  children.push(buildMainMatter(data, schema));

  // 7. Appendices
  if (data.appendices.length > 0) {
    children.push(buildAppendices(data, schema));
  }

  // 8. Bibliography
  children.push(buildBibliography(data, schema));

  // 9. \end{document}
  children.push(command('end', ['document']));

  return document(children);
}

/**
 * Generate LaTeX string from ThesisData using the AST pipeline.
 */
export function generateLatexFromAST(data: ThesisData): string {
  const ast = buildAST(data);
  return serializeDocument(ast);
}

// ============================================================
// Header Comment
// ============================================================

function buildHeaderComment(data: ThesisData): CommentNode {
  const title = data.metadata.title || 'Untitled Thesis';
  const date = new Date().toISOString().split('T')[0];
  return comment(
    `============================================================\n` +
    `${title}\n` +
    `Generated by ThesisForge\n` +
    `Date: ${date}\n` +
    `Template: ${data.type}\n` +
    `============================================================`
  );
}

// ============================================================
// Preamble Builder
// ============================================================

function buildPreamble(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];

  // Document class
  const sideOption = data.type === 'phd' ? 'twoside' : 'oneside';
  const classOptions = [...schema.classOptions];
  if (!classOptions.includes(sideOption)) {
    classOptions.push(sideOption);
  }
  // Use user's format options
  if (!classOptions.includes(data.options.fontSize)) {
    classOptions[0] = data.options.fontSize;
  }
  if (!classOptions.includes(data.options.paperSize)) {
    classOptions[1] = data.options.paperSize;
  }

  nodes.push(docClass(schema.documentClass, classOptions));
  nodes.push(blankLine());

  // Packages — ordered per spec: inputenc/fontenc first, hyperref LAST
  const packages = buildPackageList(data, schema);
  for (const pkg of packages) {
    nodes.push(usepackage(pkg.name, pkg.options));
  }
  nodes.push(blankLine());

  // Page geometry
  const marginMap: Record<string, string> = { normal: '1in', narrow: '0.75in', wide: '1.25in' };
  nodes.push(command('usepackage', [marginMap[data.options.marginSize]]));
  nodes.push(blankLine());

  // Line spacing
  if (data.options.lineSpacing !== 'single') {
    if (data.options.lineSpacing === 'onehalf') {
      nodes.push(command('onehalfspacing'));
    } else {
      nodes.push(command('doublespacing'));
    }
    nodes.push(blankLine());
  }

  // Counter settings
  if (data.options.figureNumbering === 'per-chapter') {
    nodes.push(command('counterwithin', ['figure', 'chapter']));
  }
  if (data.options.tableNumbering === 'per-chapter') {
    nodes.push(command('counterwithin', ['table', 'chapter']));
  }
  nodes.push(blankLine());

  // Code listings (if enabled)
  if (data.options.includeListings) {
    nodes.push(command('lstset', undefined, undefined));
    // We output listings config as a comment block since the AST doesn't handle complex lstset
    nodes.push(comment(
      'Listings configuration\n' +
      '  \\lstset{\n' +
      '    basicstyle=\\ttfamily\\small,\n' +
      '    breaklines=true,\n' +
      '    frame=single,\n' +
      '    numbers=left,\n' +
      '    numberstyle=\\tiny\\color{gray},\n' +
      '    keywordstyle=\\color{blue},\n' +
      '    commentstyle=\\color{green!50!black},\n' +
      '    stringstyle=\\color{red},\n' +
      '    tabsize=2,\n' +
      '    showstringspaces=false,\n' +
      '  }'
    ));
    nodes.push(blankLine());
  }

  // Hyperref setup — MUST be after all usepackage calls
  nodes.push(command('hypersetup', [
    `  pdftitle    = {${esc(data.metadata.title)}}`,
    `  pdfauthor   = {${esc(data.metadata.author)}}`,
    `  pdfsubject  = {${esc(data.metadata.subtitle || data.type + ' thesis')}}`,
    `  pdfkeywords = {${esc(data.keywords.join(', '))}}`,
    `  colorlinks  = true`,
    `  linkcolor   = blue`,
    `  citecolor   = blue`,
    `  urlcolor    = blue`,
  ]));
  nodes.push(blankLine());

  // ToC depth
  nodes.push(command('setcounter', ['tocdepth', String(data.options.tocDepth)]));
  nodes.push(command('setcounter', ['secnumdepth', String(data.options.tocDepth)]));
  nodes.push(blankLine());

  // Custom commands
  nodes.push(comment('Custom Commands'));
  nodes.push(macroDef('\\latex', '\\LaTeX\\xspace'));
  nodes.push(macroDef('\\tex', '\\TeX\\xspace'));
  nodes.push(blankLine());

  // Theorem environments (only for report class)
  if (schema.documentClass === 'report') {
    nodes.push(comment('Theorem Environments'));
    nodes.push(command('newtheorem', ['theorem', 'Theorem', 'chapter']));
    nodes.push(command('newtheorem', ['lemma', 'Lemma', 'theorem']));
    nodes.push(command('newtheorem', ['proposition', 'Proposition', 'theorem']));
    nodes.push(command('newtheorem', ['corollary', 'Corollary', 'theorem']));
    nodes.push(command('newtheorem', ['definition', 'Definition', 'chapter']));
    nodes.push(command('newtheorem', ['example', 'Example', 'chapter']));
    nodes.push(command('newtheorem', ['remark', 'Remark', 'chapter']));
    nodes.push(blankLine());
  }

  return nodes;
}

function buildPackageList(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): PackageImportNode[] {
  const pkgList: PackageImportNode[] = [];

  // Collect all package names we'll add
  const pkgNames = new Set<string>();

  // From template schema
  for (const pkg of schema.requiredPackages) {
    pkgNames.add(pkg.name);
    const existing = pkgList.find(p => p.packageName === pkg.name);
    if (!existing) {
      pkgList.push(usepackage(pkg.name, pkg.options));
    }
  }

  // Ensure critical packages are present
  const criticalPackages: Array<{ name: string; options?: string[]; before?: string }> = [
    { name: 'inputenc', options: ['utf8'] },
    { name: 'fontenc', options: ['T1'] },
    { name: 'lmodern' },
    { name: 'babel', options: ['english'] },
    { name: 'geometry' },
    { name: 'graphicx' },
    { name: 'amsmath' },
    { name: 'amssymb' },
    { name: 'booktabs' },
    { name: 'array' },
    { name: 'setspace' },
    { name: 'microtype' },
    { name: 'caption', options: ['font=small', 'labelfont=bf'] },
    { name: 'xspace' },
    { name: 'natbib', options: ['round'], before: 'hyperref' },
    { name: 'hyperref', options: ['hidelinks'] },
  ];

  // Conditionals
  if (schema.documentClass === 'report') {
    criticalPackages.push({ name: 'amsthm' });
  }
  if (data.options.figureNumbering === 'per-chapter' || data.options.tableNumbering === 'per-chapter') {
    criticalPackages.push({ name: 'chngcntr' });
  }
  if (data.options.includeListings) {
    criticalPackages.push({ name: 'listings' });
  }
  if (data.type === 'phd' && data.options.includeGlossary) {
    criticalPackages.push({ name: 'nomencl' });
    criticalPackages.push({ name: 'glossaries' });
  }

  for (const pkg of criticalPackages) {
    if (!pkgNames.has(pkg.name)) {
      pkgNames.add(pkg.name);
      pkgList.push(usepackage(pkg.name, pkg.options));
    }
  }

  // Reorder: natbib BEFORE hyperref, hyperref LAST
  const hyperrefIdx = pkgList.findIndex(p => p.packageName === 'hyperref');
  const natbibIdx = pkgList.findIndex(p => p.packageName === 'natbib');

  if (hyperrefIdx > -1) {
    const hyperrefPkg = pkgList.splice(hyperrefIdx, 1)[0];
    pkgList.push(hyperrefPkg);
  }
  if (natbibIdx > -1) {
    const natbibPkg = pkgList.splice(natbibIdx > (hyperrefIdx > -1 && natbibIdx > hyperrefIdx ? natbibIdx - 1 : natbibIdx), 1)[0];
    // Insert before the last item (hyperref)
    pkgList.splice(pkgList.length - 1, 0, natbibPkg);
  }

  return pkgList;
}

// ============================================================
// Title Page Builder
// ============================================================

function buildTitlePage(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const { metadata } = data;

  nodes.push(comment('Title Page'));
  nodes.push(blankLine());

  const titlePageChildren: ASTNode[] = [];

  titlePageChildren.push(command('centering'));
  titlePageChildren.push(blankLine());

  if (metadata.university) {
    titlePageChildren.push(command('scshape'));
    titlePageChildren.push(command('Large'));
    titlePageChildren.push(text(esc(metadata.university)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }
  if (metadata.faculty) {
    titlePageChildren.push(command('scshape'));
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text(esc(metadata.faculty)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }
  if (metadata.department) {
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text(esc(metadata.department)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }

  titlePageChildren.push(command('vspace', ['1.5cm']));
  titlePageChildren.push(blankLine());

  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'Doctoral Dissertation',
    report: 'Research Report',
  };
  titlePageChildren.push(command('Large', [], ['bfseries']));
  titlePageChildren.push(text(esc(typeLabels[data.type])));
  titlePageChildren.push(command('par'));
  titlePageChildren.push(blankLine());

  titlePageChildren.push(command('vspace', ['1cm']));
  titlePageChildren.push(blankLine());

  titlePageChildren.push(command('LARGE', [], ['bfseries']));
  titlePageChildren.push(text(esc(metadata.title)));
  titlePageChildren.push(command('par'));
  titlePageChildren.push(blankLine());

  if (metadata.subtitle) {
    titlePageChildren.push(command('large', [], ['itshape']));
    titlePageChildren.push(text(esc(metadata.subtitle)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }

  titlePageChildren.push(command('vspace', ['2cm']));
  titlePageChildren.push(blankLine());

  titlePageChildren.push(command('large'));
  titlePageChildren.push(text('Submitted by:'));
  titlePageChildren.push(command('par'));
  titlePageChildren.push(command('vspace', ['0.3cm']));
  titlePageChildren.push(command('Large', [], ['bfseries']));
  titlePageChildren.push(text(esc(metadata.author)));
  titlePageChildren.push(command('par'));
  titlePageChildren.push(blankLine());

  if (metadata.authorId) {
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text('Student ID: ' + esc(metadata.authorId)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }

  titlePageChildren.push(command('vspace', ['1.5cm']));
  titlePageChildren.push(blankLine());

  if (metadata.supervisor) {
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text('Supervisor:'));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text(esc(metadata.supervisorTitle || 'Prof.') + ' ' + esc(metadata.supervisor)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }
  if (metadata.coSupervisor) {
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text('Co-Supervisor:'));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text(esc(metadata.coSupervisorTitle || 'Dr.') + ' ' + esc(metadata.coSupervisor)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }

  titlePageChildren.push(command('vspace', ['1.5cm']));
  titlePageChildren.push(blankLine());

  if (metadata.location && metadata.submissionDate) {
    const dateObj = new Date(metadata.submissionDate);
    const formattedDate = dateObj.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    titlePageChildren.push(command('large'));
    titlePageChildren.push(text(esc(metadata.location) + ', ' + esc(formattedDate)));
    titlePageChildren.push(command('par'));
    titlePageChildren.push(blankLine());
  }

  nodes.push(environment('titlepage', titlePageChildren));
  nodes.push(blankLine());

  return nodes;
}

// ============================================================
// Front Matter Builder
// ============================================================

function buildFrontMatter(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const { metadata, abstract, keywords, options } = data;

  nodes.push(comment('Front Matter'));
  nodes.push(command('frontmatter'));
  nodes.push(blankLine());

  // Dedication
  if (options.includeDedication && metadata.dedication) {
    nodes.push(comment('Dedication'));
    const dedChildren: ASTNode[] = [
      command('vspace', ['*{\\fill}']),
      command('begin', ['center']),
      command('large', [], ['itshape']),
      text(esc(metadata.dedication)),
      command('end', ['center']),
      command('vspace', ['*{\\fill}']),
    ];
    nodes.push(environment('dedication', dedChildren));
    nodes.push(blankLine());
  }

  // Acknowledgments
  if (options.includeAcknowledgment && metadata.acknowledgment) {
    nodes.push(comment('Acknowledgments'));
    const absCmd = data.type === 'report' ? 'section' : 'chapter';
    nodes.push(command(absCmd, ['Acknowledgments'], ['*']));
    nodes.push(command('addcontentsline', ['toc', data.type === 'report' ? 'section' : 'chapter', 'Acknowledgments']));
    nodes.push(blankLine());
    nodes.push(...contentToNodes(metadata.acknowledgment));
    nodes.push(blankLine());
  }

  // Abstract
  nodes.push(comment('Abstract'));
  const absLabel = data.type === 'report' ? 'section' : 'chapter';
  nodes.push(command(absLabel, ['Abstract'], ['*']));
  nodes.push(command('addcontentsline', ['toc', data.type === 'report' ? 'section' : 'chapter', 'Abstract']));
  nodes.push(blankLine());
  if (abstract) {
    nodes.push(...contentToNodes(abstract));
  }
  if (keywords.length > 0) {
    nodes.push(blankLine());
    nodes.push(command('noindent'));
    nodes.push(command('textbf', ['Keywords: ']));
    nodes.push(text(keywords.map(esc).join(', ')));
    nodes.push(blankLine());
  }
  nodes.push(blankLine());

  // Table of Contents
  nodes.push(comment('Table of Contents'));
  nodes.push(command('tableofcontents'));
  nodes.push(blankLine());

  // List of Figures
  nodes.push(command('listoffigures'));
  nodes.push(blankLine());

  // List of Tables
  nodes.push(command('listoftables'));
  nodes.push(blankLine());

  return nodes;
}

// ============================================================
// Main Matter Builder
// ============================================================

function buildMainMatter(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];

  nodes.push(comment('Main Matter'));
  nodes.push(command('mainmatter'));
  nodes.push(blankLine());

  for (const chapter of data.chapters) {
    nodes.push(buildChapter(chapter, data.type, schema));
  }

  return nodes;
}

function buildChapter(chapter: ThesisChapter, type: ThesisType, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];
  const chCmd = schema.chapterCommand; // \chapter or \section

  nodes.push(comment(`${chCmd === '\\chapter' ? 'Chapter' : 'Section'} ${chapter.number}: ${chapter.title}`));
  nodes.push(command(chCmd.replace('\\', ''), [esc(chapter.title)]));
  nodes.push(blankLine());

  // Chapter content
  if (chapter.content && chapter.content.trim()) {
    nodes.push(...contentToNodes(chapter.content));
    nodes.push(blankLine());
  }

  // Subsections
  const secCmd = type === 'report' ? 'subsection' : 'section';
  for (const sub of chapter.subSections) {
    if (sub.title?.trim()) {
      nodes.push(command(secCmd, [esc(sub.title)]));
      nodes.push(blankLine());
      if (sub.content && sub.content.trim()) {
        nodes.push(...contentToNodes(sub.content));
        nodes.push(blankLine());
      }
    }
  }

  return nodes;
}

// ============================================================
// Appendices Builder
// ============================================================

function buildAppendices(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];

  nodes.push(comment('Appendices'));
  nodes.push(command('appendix'));
  nodes.push(blankLine());

  for (const appendix of data.appendices) {
    const chCmd = schema.chapterCommand;
    nodes.push(command(chCmd.replace('\\', ''), [esc(appendix.title)]));
    nodes.push(blankLine());
    if (appendix.content && appendix.content.trim()) {
      nodes.push(...contentToNodes(appendix.content));
      nodes.push(blankLine());
    }
  }

  return nodes;
}

// ============================================================
// Bibliography Builder
// ============================================================

function buildBibliography(data: ThesisData, schema: typeof TEMPLATE_SCHEMAS[string]): ASTNode[] {
  const nodes: ASTNode[] = [];

  nodes.push(comment('Bibliography'));
  nodes.push(command('backmatter'));
  nodes.push(blankLine());

  if (data.references.length === 0) {
    nodes.push(comment('No references added yet. Add references in Step 4 to populate this section.'));
    nodes.push(blankLine());
    return nodes;
  }

  // Use thebibliography for zero-config compilability
  nodes.push(command('begin', ['thebibliography', String(data.references.length)]));
  nodes.push(blankLine());
  nodes.push(command('bibliographystyle', ['plainnat']));
  nodes.push(blankLine());

  for (let i = 0; i < data.references.length; i++) {
    const ref = data.references[i];
    const key = generateCiteKey(ref, i);
    const entryText = formatBibItemInline(ref);
    nodes.push(text(`  \\bibitem{${key}} ${entryText}`));
    nodes.push(blankLine());
  }

  nodes.push(command('end', ['thebibliography']));
  nodes.push(blankLine());

  // Include BibTeX source as comment block for advanced users
  nodes.push(comment(
    'BibTeX Source (for BibTeX workflow)\n' +
    'To use: uncomment \\bibliography{references} and remove thebibliography above'
  ));
  nodes.push(blankLine());

  for (let i = 0; i < data.references.length; i++) {
    const ref = data.references[i];
    const bibEntry = formatBibTeXEntry(ref, i);
    nodes.push(comment(bibEntry));
    nodes.push(blankLine());
  }

  return nodes;
}

// ============================================================
// Content Conversion — Plain text to AST nodes
// ============================================================

function contentToNodes(content: string): ASTNode[] {
  if (!content || !content.trim()) return [];

  const paragraphs = content.split(/\n\s*\n/).filter(p => p.trim());
  const nodes: ASTNode[] = [];

  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) continue;

    // Handle figure/table placeholders
    const parts = splitPlaceholders(trimmed);
    for (const part of parts) {
      if (part.type === 'figure') {
        nodes.push(...buildFigurePlaceholder(part.caption || ''));
      } else if (part.type === 'table') {
        nodes.push(...buildTablePlaceholder(part.caption || ''));
      } else {
        // Regular text content
        const lines = part.content.split('\n');
        for (let j = 0; j < lines.length; j++) {
          if (j > 0) {
            nodes.push(text('\\\\'));
          }
          const line = lines[j].trim();
          if (line) {
            nodes.push(text(esc(line)));
          }
        }
        nodes.push(blankLine());
      }
    }
  }

  return nodes;
}

interface ContentPart {
  type: 'text' | 'figure' | 'table';
  content: string;
  caption?: string;
}

function splitPlaceholders(content: string): ContentPart[] {
  const parts: ContentPart[] = [];
  const figureRegex = /\[figure\](?::([^\]]*))?/g;
  const tableRegex = /\[table\](?::([^\]]*))?/g;

  // Simple split: find all placeholder positions
  const tokens: Array<{ pos: number; len: number; type: 'figure' | 'table'; caption: string }> = [];

  let match: RegExpExecArray | null;
  while ((match = figureRegex.exec(content)) !== null) {
    tokens.push({ pos: match.index, len: match[0].length, type: 'figure', caption: match[1] || '' });
  }
  while ((match = tableRegex.exec(content)) !== null) {
    tokens.push({ pos: match.index, len: match[0].length, type: 'table', caption: match[1] || '' });
  }

  if (tokens.length === 0) {
    return [{ type: 'text', content }];
  }

  // Sort by position
  tokens.sort((a, b) => a.pos - b.pos);

  let lastEnd = 0;
  for (const token of tokens) {
    if (token.pos > lastEnd) {
      parts.push({ type: 'text', content: content.slice(lastEnd, token.pos) });
    }
    parts.push({ type: token.type, content: '', caption: token.caption });
    lastEnd = token.pos + token.len;
  }

  if (lastEnd < content.length) {
    parts.push({ type: 'text', content: content.slice(lastEnd) });
  }

  return parts;
}

function buildFigurePlaceholder(caption: string): ASTNode[] {
  const cap = caption || '[Caption here]';
  return [
    environment('figure', [
      blankLine(),
      command('centering'),
      command('includegraphics', ['width=0.8\\textwidth'], ['figures/placeholder']),
      command('caption', [esc(cap)]),
      command('label', ['fig:placeholder']),
      blankLine(),
    ], ['htbp']),
    blankLine(),
  ];
}

function buildTablePlaceholder(caption: string): ASTNode[] {
  const cap = caption || '[Caption here]';
  return [
    environment('table', [
      blankLine(),
      command('centering'),
      command('caption', [esc(cap)]),
      command('label', ['tab:placeholder']),
      blankLine(),
      comment('Replace with your table content'),
      text('\\begin{tabular}{lcc}'),
      text('\\toprule'),
      text('Header 1 & Header 2 & Header 3 \\\\'),
      text('\\midrule'),
      text('Data 1 & Data 2 & Data 3 \\\\'),
      text('Data 4 & Data 5 & Data 6 \\\\'),
      text('\\bottomrule'),
      text('\\end{tabular}'),
      blankLine(),
    ], ['htbp']),
    blankLine(),
  ];
}

// ============================================================
// Bibliography Formatting Helpers
// ============================================================

function generateCiteKey(ref: ThesisReference, index: number): string {
  let authorPart = 'unknown';
  if (ref.authors) {
    const firstAuthor = ref.authors.split(',')[0].trim();
    const parts = firstAuthor.split(/\s+/);
    authorPart = (parts[parts.length - 1] || firstAuthor)
      .toLowerCase()
      .replace(/[^a-z]/g, '');
  }
  const yearPart = ref.year || '0000';
  let titlePart = '';
  if (ref.title) {
    titlePart = ref.title.split(/\s+/)[0].toLowerCase().replace(/[^a-z]/g, '').slice(0, 8);
  }
  return `${authorPart}${yearPart}${titlePart}${index}`;
}

function formatBibItemInline(ref: ThesisReference): string {
  let entry = `${esc(ref.authors)}, `;

  switch (ref.type) {
    case 'book':
      entry += `\\textit{${esc(ref.title)}}`;
      if (ref.edition) entry += `, ${esc(ref.edition)} edition`;
      if (ref.publisher) entry += `, ${esc(ref.publisher)}`;
      if (ref.address) entry += `, ${esc(ref.address)}`;
      if (ref.year) entry += `, ${esc(ref.year)}`;
      entry += '.';
      break;
    case 'article':
      entry += `\\textit{${esc(ref.title)}}, `;
      if (ref.journal) entry += `${esc(ref.journal)}, `;
      if (ref.volume) entry += `vol.~${esc(ref.volume)}, `;
      if (ref.number) entry += `no.~${esc(ref.number)}, `;
      if (ref.pages) entry += `pp.~${esc(ref.pages)}, `;
      if (ref.year) entry += `${esc(ref.year)}`;
      entry += '.';
      break;
    case 'inproceedings':
      entry += `\\textit{${esc(ref.title)}}, `;
      if (ref.bookTitle) entry += `in \\textit{${esc(ref.bookTitle)}}, `;
      if (ref.pages) entry += `pp.~${esc(ref.pages)}, `;
      if (ref.year) entry += `${esc(ref.year)}`;
      entry += '.';
      break;
    case 'online':
      entry += `\\textit{${esc(ref.title)}}, `;
      if (ref.url) entry += `\\url{${ref.url}}, `;
      if (ref.accessed) entry += `accessed: ${esc(ref.accessed)}`;
      entry += '.';
      break;
    case 'thesis':
      entry += `\\textit{${esc(ref.title)}}, `;
      if (ref.school) entry += `${esc(ref.school)}, `;
      if (ref.year) entry += `${esc(ref.year)}`;
      entry += '.';
      break;
    default:
      entry += `\\textit{${esc(ref.title)}}`;
      if (ref.year) entry += `, ${esc(ref.year)}`;
      entry += '.';
  }

  return entry;
}

function formatBibTeXEntry(ref: ThesisReference, index: number): string {
  const key = generateCiteKey(ref, index);
  const typeMap: Record<string, string> = {
    article: 'article',
    book: 'book',
    inproceedings: 'inproceedings',
    techreport: 'techreport',
    thesis: 'phdthesis',
    online: 'online',
    misc: 'misc',
  };
  const bibType = typeMap[ref.type] || 'misc';

  const fields: string[] = [];
  fields.push(`  author  = {${ref.authors || ''}}`);
  fields.push(`  title   = {${ref.title || ''}}`);

  if (ref.journal) fields.push(`  journal = {${ref.journal}}`);
  if (ref.bookTitle) fields.push(`  booktitle = {${ref.bookTitle}}`);
  if (ref.publisher) fields.push(`  publisher = {${ref.publisher}}`);
  if (ref.school) fields.push(`  school = {${ref.school}}`);
  if (ref.year) fields.push(`  year = {${ref.year}}`);
  if (ref.volume) fields.push(`  volume = {${ref.volume}}`);
  if (ref.number) fields.push(`  number = {${ref.number}}`);
  if (ref.pages) fields.push(`  pages = {${ref.pages}}`);
  if (ref.edition) fields.push(`  edition = {${ref.edition}}`);
  if (ref.address) fields.push(`  address = {${ref.address}}`);
  if (ref.doi) fields.push(`  doi = {${ref.doi}}`);
  if (ref.url) fields.push(`  url = {${ref.url}}`);
  if (ref.accessed) fields.push(`  urldate = {${ref.accessed}}`);
  if (ref.note) fields.push(`  note = {${ref.note}}`);
  if (ref.howPublished) fields.push(`  howpublished = {${ref.howPublished}}`);

  return `@${bibType}{${key},\n${fields.join(',\n')}\n}`;
}

// ============================================================
// Utility — Escape shorthand
// ============================================================

function esc(str: string): string {
  return escapeLatex(str);
}
