// ============================================================
// ThesisForge Core — Export Pipeline
// Client-side ZIP generation. Zero server dependency.
// ============================================================

import JSZip from 'jszip';
import { sanitizeFilename } from '@/utils/latex-escape';
import type { ThesisData, ThesisType } from '@/lib/thesis-types';
import { generateLatex } from '@/lib/latex-generator';
import { generateBibFile } from '@/core/bib';

// ============================================================
// README Generator
// ============================================================

function generateReadme(data: ThesisData, templateId: ThesisType): string {
  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'PhD Dissertation',
    report: 'Research Report',
  };

  const templateLabel = typeLabels[templateId] || 'Thesis';

  return `# ${data.metadata.title || 'Untitled ' + templateLabel}

${data.metadata.author ? `**Author:** ${data.metadata.author}` : ''}
${data.metadata.university ? `**University:** ${data.metadata.university}` : ''}
${data.metadata.supervisor ? `**Supervisor:** ${data.metadata.supervisor}` : ''}

---

## File Structure

| File | Description |
|------|-------------|
| \`main.tex\` | Main LaTeX source file — compile this |
| \`references.bib\` | BibTeX bibliography database |
| \`README.md\` | This file — compilation instructions |
${data.options.includeListings ? '| `figures/` | Folder for figures and images |' : ''}

## How to Compile

### Option 1: Local LaTeX Installation

\`\`\`bash
# If using BibTeX:
pdflatex main.tex
bibtex main
pdflatex main.tex
pdflatex main.tex

# If using thebibliography (default):
pdflatex main.tex
pdflatex main.tex
\`\`\`

### Option 2: Overleaf (Recommended)

1. Go to [overleaf.com](https://www.overleaf.com)
2. Create a new blank project
3. Upload \`main.tex\` and \`references.bib\`
4. Click **Compile**
5. Your PDF will be generated automatically

### Option 3: Docker

\`\`\`bash
docker run --rm -v $(pwd):/data blang/latex:ubuntu pdflatex /data/main.tex
\`\`\`

## Required Packages

The following LaTeX packages are used in \`main.tex\`:

${getRequiredPackagesList(templateId, data.options)}

## Template Type

This document uses the **${templateLabel}** template generated by ThesisForge.

## Compilation Order

For documents with citations:

1. \`pdflatex main.tex\` — First pass (resolves references)
2. \`bibtex main\` — Generates bibliography
3. \`pdflatex main.tex\` — Second pass (includes citations)
4. \`pdflatex main.tex\` — Third pass (resolves all cross-references)

For documents without citations:

1. \`pdflatex main.tex\`
2. \`pdflatex main.tex\`

---

*Generated by [ThesisForge](https://thesisforge.vercel.app) — ${new Date().toISOString().split('T')[0]}*
`;
}

function getRequiredPackagesList(templateId: ThesisType, options: ThesisData['options']): string {
  const common = [
    'inputenc (utf8)',
    'fontenc (T1)',
    'lmodern',
    'babel (english)',
    'geometry',
    'graphicx',
    'amsmath',
    'amssymb',
    'amsthm',
    'booktabs',
    'array',
    'multirow',
    'longtable',
    'setspace',
    'microtype',
    'hyperref',
    'natbib',
  ];

  if (templateId === 'phd') {
    common.push('nomencl', 'glossaries', 'chngcntr');
  }
  if (templateId === 'master') {
    common.push('chngcntr');
  }
  if (options.includeListings) {
    common.push('listings');
  }

  return common.map(p => `- \`${p}\``).join('\n');
}

// ============================================================
// Export Pipeline
// ============================================================

/**
 * Export thesis as a ZIP file.
 * Runs entirely client-side. No server required.
 */
export async function exportThesis(
  data: ThesisData,
  templateId: ThesisType
): Promise<void> {
  const tex = generateLatex(data);
  const bib = generateBibFile(
    data.references.map(ref => ({
      type: (ref.type === 'thesis' ? 'phdthesis' : ref.type === 'techreport' ? 'techreport' : ref.type) as 'article' | 'book' | 'inproceedings' | 'techreport' | 'phdthesis' | 'online' | 'misc',
      fields: {
        authors: ref.authors || '',
        title: ref.title || '',
        journal: ref.journal || '',
        bookTitle: ref.bookTitle || '',
        publisher: ref.publisher || '',
        year: ref.year || '',
        volume: ref.volume || '',
        number: ref.number || '',
        pages: ref.pages || '',
        doi: ref.doi || '',
        url: ref.url || '',
        note: ref.note || '',
        edition: ref.edition || '',
        address: ref.address || '',
        school: ref.school || '',
        institution: ref.publisher || '',
        howPublished: ref.howPublished || '',
        accessed: ref.accessed || '',
        month: '',
        isbn: '',
        organization: '',
        type: ref.type === 'thesis' ? 'phdthesis' : ref.type,
      },
    }))
  );
  const readme = generateReadme(data, templateId);

  const zip = new JSZip();
  const folderName = sanitizeFilename(data.metadata.title) || 'thesis';
  const folder = zip.folder(folderName);

  if (!folder) throw new Error('Failed to create ZIP folder');

  folder.file('main.tex', tex);
  folder.file('references.bib', bib);
  folder.file('README.md', readme);

  // Add figures folder placeholder if needed
  if (data.options.includeListings || data.options.includeFiguresFolder !== false) {
    folder.folder('figures').file('.gitkeep', '');
  }

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  triggerDownload(blob, `${folderName}.zip`);
}

/**
 * Export just the .tex file.
 */
export async function exportTexOnly(data: ThesisData): Promise<void> {
  const tex = generateLatex(data);
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([tex], { type: 'text/x-tex' });
  triggerDownload(blob, `${filename}.tex`);
}

/**
 * Export just the .bib file.
 */
export async function exportBibOnly(data: ThesisData): Promise<void> {
  const bib = generateBibFile(
    data.references.map(ref => ({
      type: 'article' as const,
      fields: {
        authors: ref.authors || '',
        title: ref.title || '',
        year: ref.year || '',
      },
    }))
  );
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([bib], { type: 'text/plain' });
  triggerDownload(blob, `${filename}_references.bib`);
}

/**
 * Trigger a file download in the browser.
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
