// ============================================================
// ThesisForge Core — Export Pipeline (Engine v3)
// Client-side ZIP generation. Zero server dependency.
// Now uses the expanded contract system with 30 checks
// and the enhanced bibliography engine.
// ============================================================

import JSZip from 'jszip';
import { sanitizeFilename } from '@/utils/latex-escape';
import type { ThesisData, ThesisType } from '@/lib/thesis-types';
import { generateLatex } from '@/lib/latex-generator';
import { generateBibFromThesisReferences } from '@/core/bib';
import { assertLatexContract, contractSummary, type LatexContractError } from '@/core/latexAssertions';
import { runIntelligence, type IntelligenceReport } from '@/engine/intelligence';

// ============================================================
// README Generator
// ============================================================

function generateReadme(data: ThesisData, templateId: ThesisType): string {
  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'PhD Dissertation',
    report: 'Research Report',
  };

  const templateLabel = typeLabels[templateId] || 'Thesis';

  return `# ${data.metadata.title || 'Untitled ' + templateLabel}

${data.metadata.author ? `**Author:** ${data.metadata.author}` : ''}
${data.metadata.university ? `**University:** ${data.metadata.university}` : ''}
${data.metadata.supervisor ? `**Supervisor:** ${data.metadata.supervisor}` : ''}

---

## File Structure

| File | Description |
|------|-------------|
| \`main.tex\` | Main LaTeX source file — compile this |
| \`references.bib\` | BibTeX bibliography database |
| \`README.md\` | This file — compilation instructions |
${data.options.includeListings ? '| `figures/` | Folder for figures and images |' : ''}

## How to Compile

### Option 1: Local LaTeX Installation

\`\`\`bash
# If using BibTeX:
pdflatex main.tex
bibtex main
pdflatex main.tex
pdflatex main.tex

# If using thebibliography (default):
pdflatex main.tex
pdflatex main.tex
\`\`\`

### Option 2: Overleaf (Recommended)

1. Go to [overleaf.com](https://www.overleaf.com)
2. Create a new blank project
3. Upload \`main.tex\` and \`references.bib\`
4. Click **Compile**
5. Your PDF will be generated automatically

### Option 3: Docker

\`\`\`bash
docker run --rm -v $(pwd):/data blang/latex:ubuntu pdflatex /data/main.tex
\`\`\`

## Required Packages

The following LaTeX packages are used in \`main.tex\`:

${getRequiredPackagesList(templateId, data.options)}

## Template Type

This document uses the **${templateLabel}** template generated by ThesisForge.

## Compilation Order

For documents with citations:

1. \`pdflatex main.tex\` — First pass (resolves references)
2. \`bibtex main\` — Generates bibliography
3. \`pdflatex main.tex\` — Second pass (includes citations)
4. \`pdflatex main.tex\` — Third pass (resolves all cross-references)

For documents without citations:

1. \`pdflatex main.tex\`
2. \`pdflatex main.tex\`

---

*Generated by [ThesisForge](https://thesisforge.vercel.app) — ${new Date().toISOString().split('T')[0]}*
`;
}

function getRequiredPackagesList(templateId: ThesisType, options: ThesisData['options']): string {
  const common = [
    'inputenc (utf8)',
    'fontenc (T1)',
    'lmodern',
    'babel (english)',
    'geometry',
    'graphicx',
    'amsmath',
    'amssymb',
    'booktabs',
    'array',
    'multirow',
    'longtable',
    'tabularx',
    'setspace',
    'microtype',
    'caption',
    'enumitem',
    'fancyhdr',
    'xspace',
    'natbib',
    'hyperref',
    'cleveref',
  ];

  if (templateId === 'phd') {
    common.push('nomencl', 'glossaries', 'chngcntr', 'amsthm', 'mathtools');
  }
  if (templateId === 'master') {
    common.push('chngcntr', 'amsthm');
  }
  if (templateId === 'bachelor') {
    common.push('amsthm');
  }
  if (options.includeListings) {
    common.push('listings', 'xcolor');
  }

  return common.map(p => `- \`${p}\``).join('\n');
}

// ============================================================
// Export Pipeline
// ============================================================

export interface ExportResult {
  errors?: LatexContractError[];
  contractSummary?: ReturnType<typeof contractSummary>;
  intelligence?: IntelligenceReport;
}

/**
 * Export thesis as a ZIP file.
 * Runs entirely client-side. No server required.
 *
 * v3: Runs expanded 30-check contract + intelligence analysis.
 * Returns results for UI display.
 */
export async function exportThesis(
  data: ThesisData,
  templateId: ThesisType
): Promise<ExportResult> {
  try {
    const tex = generateLatex(data);

    // Use enhanced BibTeX generation from bib.ts
    const bib = generateBibFromThesisReferences(data.references);

    const readme = generateReadme(data, templateId);

    // Run expanded 30-check contract
    const contractErrors = assertLatexContract(tex, bib, data, 'warning');
    const summary = contractSummary(tex, bib, data);

    // Run intelligence analysis
    const intelligence = await runIntelligence(data);

    // Block export on errors only (warnings and info don't block)
    // Severity filtering: only C01-C06 are errors, C07+ are warnings
    const hasErrors = contractErrors.some(e => {
      return e.code === 'C01' || e.code === 'C02' || e.code === 'C03' ||
             e.code === 'C04' || e.code === 'C05' || e.code === 'C06';
    });

    if (hasErrors) {
      return { errors: contractErrors, contractSummary: summary, intelligence };
    }

    const zip = new JSZip();
    const folderName = sanitizeFilename(data.metadata.title) || 'thesis';
    const folder = zip.folder(folderName);

    if (!folder) throw new Error('Failed to create ZIP folder');

    folder.file('main.tex', tex);
    folder.file('references.bib', bib);
    folder.file('README.md', readme);

    // Add figures folder placeholder
    const figuresFolder = folder.folder('figures');
    if (figuresFolder) {
      figuresFolder.file('.gitkeep', '');
    }

    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    triggerDownload(blob, `${folderName}.zip`);

    return {
      errors: contractErrors.length > 0 ? contractErrors : undefined,
      contractSummary: summary,
      intelligence,
    };
  } catch (err) {
    throw err;
  }
}

/**
 * Export just the .tex file.
 */
export async function exportTexOnly(data: ThesisData): Promise<void> {
  const tex = generateLatex(data);
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([tex], { type: 'text/x-tex' });
  triggerDownload(blob, `${filename}.tex`);
}

/**
 * Export just the .bib file.
 */
export async function exportBibOnly(data: ThesisData): Promise<void> {
  const bib = generateBibFromThesisReferences(data.references);
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([bib], { type: 'text/plain' });
  triggerDownload(blob, `${filename}_references.bib`);
}

/**
 * Run contract checks without exporting.
 * Used by the UI to show lint results.
 */
export async function runContractChecks(data: ThesisData): Promise<ExportResult> {
  const tex = generateLatex(data);
  const bib = generateBibFromThesisReferences(data.references);
  const contractErrors = assertLatexContract(tex, bib, data, 'info');
  const summary = contractSummary(tex, bib, data);
  const intelligence = await runIntelligence(data);

  return {
    errors: contractErrors.length > 0 ? contractErrors : undefined,
    contractSummary: summary,
    intelligence,
  };
}

/**
 * Trigger a file download in the browser.
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
