// ============================================================
// ThesisForge Core — Export Pipeline (Engine v3)
// Client-side ZIP generation. Zero server dependency.
// Now uses the expanded contract system with 30 checks
// and the enhanced bibliography engine.
// ============================================================

import JSZip from 'jszip';
import { sanitizeFilename } from '@/utils/latex-escape';
import type { ThesisData, ThesisType, CitationStyle } from '@/lib/thesis-types';
import { generateLatex } from '@/lib/latex-generator';
import { generateBibFromThesisReferences } from '@/core/bib';
import { assertLatexContract, contractSummary, getFullContractReport, type LatexContractError } from '@/core/latexAssertions';
import { runIntelligence, type IntelligenceReport, countWords } from '@/engine/intelligence';

// ============================================================
// Export Types
// ============================================================

export interface ChecklistItem {
  id: string;
  category: 'compilability' | 'packages' | 'structure' | 'bibliography' | 'metadata' | 'quality';
  passed: boolean;
  message: string;
  severity: 'error' | 'warning' | 'info';
}

export interface ExportResult {
  errors?: LatexContractError[];
  contractSummary?: ReturnType<typeof contractSummary>;
  intelligence?: IntelligenceReport;
  checklist?: ChecklistItem[];
  healthScore?: number;
}

// ============================================================
// README Generator
// ============================================================

function generateReadme(data: ThesisData, templateId: ThesisType): string {
  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'PhD Dissertation',
    report: 'Research Report',
    conference: 'Conference Paper',
  };

  const templateLabel = typeLabels[templateId] || 'Thesis';

  return `# ${data.metadata.title || 'Untitled ' + templateLabel}

${data.metadata.author ? `**Author:** ${data.metadata.author}` : ''}
${data.metadata.university ? `**University:** ${data.metadata.university}` : ''}
${data.metadata.supervisor ? `**Supervisor:** ${data.metadata.supervisor}` : ''}

---

## File Structure

| File | Description |
|------|-------------|
| \`main.tex\` | Main LaTeX source file — compile this |
| \`references.bib\` | BibTeX bibliography database |
| \`README.md\` | This file — compilation instructions |
| \`COMPILE.md\` | Detailed compilation guide and troubleshooting |
${data.options.includeListings ? '| `figures/` | Folder for figures and images |' : ''}

## How to Compile

### Option 1: Local LaTeX Installation

\`\`\`bash
# If using BibTeX:
pdflatex main.tex
bibtex main
pdflatex main.tex
pdflatex main.tex

# If using thebibliography (default):
pdflatex main.tex
pdflatex main.tex
\`\`\`

### Option 2: Overleaf (Recommended)

1. Go to [overleaf.com](https://www.overleaf.com)
2. Create a new blank project
3. Upload \`main.tex\` and \`references.bib\`
4. Click **Compile**
5. Your PDF will be generated automatically

### Option 3: Docker

\`\`\`bash
docker run --rm -v $(pwd):/data blang/latex:ubuntu pdflatex /data/main.tex
\`\`\`

## Required Packages

The following LaTeX packages are used in \`main.tex\`:

${getRequiredPackagesList(templateId, data.options)}

## Template Type

This document uses the **${templateLabel}** template generated by ThesisForge.

## Compilation Order

For documents with citations:

1. \`pdflatex main.tex\` — First pass (resolves references)
2. \`bibtex main\` — Generates bibliography
3. \`pdflatex main.tex\` — Second pass (includes citations)
4. \`pdflatex main.tex\` — Third pass (resolves all cross-references)

For documents without citations:

1. \`pdflatex main.tex\`
2. \`pdflatex main.tex\`

---

*Generated by [ThesisForge](https://thesisforge.vercel.app) — ${new Date().toISOString().split('T')[0]}*
`;
}

function getRequiredPackagesList(templateId: ThesisType, options: ThesisData['options']): string {
  const common = [
    'inputenc (utf8)',
    'fontenc (T1)',
    'lmodern',
    'babel (english)',
    'geometry',
    'graphicx',
    'amsmath',
    'amssymb',
    'booktabs',
    'array',
    'multirow',
    'longtable',
    'tabularx',
    'setspace',
    'microtype',
    'caption',
    'enumitem',
    'fancyhdr',
    'xspace',
    'natbib',
    'hyperref',
    'cleveref',
  ];

  if (templateId === 'phd') {
    common.push('nomencl', 'glossaries', 'chngcntr', 'amsthm', 'mathtools');
  }
  if (templateId === 'master') {
    common.push('chngcntr', 'amsthm');
  }
  if (templateId === 'bachelor') {
    common.push('amsthm');
  }
  if (options.includeListings) {
    common.push('listings', 'xcolor');
  }

  return common.map(p => `- \`${p}\``).join('\n');
}

// ============================================================
// COMPILE.md Generator
// ============================================================

/**
 * Generate a detailed COMPILE.md with step-by-step compilation
 * instructions, troubleshooting, and package dependency list.
 */
export function generateCompileMd(data: ThesisData, templateId: ThesisType): string {
  const typeLabels: Record<ThesisType, string> = {
    bachelor: "Bachelor's Thesis",
    master: "Master's Thesis",
    phd: 'PhD Dissertation',
    report: 'Research Report',
    conference: 'Conference Paper',
  };

  const templateLabel = typeLabels[templateId] || 'Thesis';
  const title = data.metadata.title || 'Untitled Thesis';
  const hasBib = data.references.length > 0;
  const usesBibLaTeX = data.options.citationStyle === 'apa' || data.options.citationStyle === 'harvard';
  const bibTool = usesBibLaTeX ? 'biber' : 'bibtex';
  const bibToolLabel = usesBibLaTeX ? 'Biber' : 'BibTeX';
  const generatedDate = new Date().toISOString().split('T')[0];
  const safeTitle = sanitizeFilename(title);

  const lines: string[] = [];

  // ── Header ──
  lines.push(`# Compilation Guide — ${title}`);
  lines.push('');
  lines.push(`> **Template:** ${templateLabel}`);
  lines.push(`> **Generated:** ${generatedDate}`);
  lines.push(`> **Generated by:** ThesisForge v2.0`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Table of Contents ──
  lines.push('## Table of Contents');
  lines.push('');
  lines.push('1. [Quick Start (Overleaf)](#quick-start-overleaf)');
  lines.push('2. [Local Compilation with pdfLaTeX](#local-compilation-with-pdflatex)');
  lines.push('3. [XeLaTeX Alternative](#xelatex-alternative)');
  lines.push('4. [LuaLaTeX Alternative](#lualatex-alternative)');
  lines.push('5. [Package Dependencies](#package-dependencies)');
  lines.push('6. [Common Errors & Solutions](#common-errors--solutions)');
  lines.push('7. [Troubleshooting Checklist](#troubleshooting-checklist)');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Quick Start (Overleaf) ──
  lines.push('## Quick Start (Overleaf)');
  lines.push('');
  lines.push('**Overleaf is the easiest way to compile your thesis.** No installation required.');
  lines.push('');
  lines.push('### Steps:');
  lines.push('');
  lines.push('1. **Create a project**');
  lines.push('   - Go to [overleaf.com](https://www.overleaf.com) and sign in (or create a free account).');
  lines.push('   - Click **"New Project"** → **"Blank Project"**.');
  lines.push(`   - Give it a name (e.g., \`${safeTitle}\`).`);
  lines.push('');
  lines.push('2. **Upload your files**');
  lines.push('   - Click the **"Upload"** button (↑ icon) in the top-left file panel.');
  lines.push('   - Upload **all** files from this ZIP:');
  lines.push('     - `main.tex` — your thesis source');
  lines.push('     - `references.bib` — your bibliography database');
  lines.push('     - `figures/` folder (if present) — your images');
  lines.push('   - Drag and drop works too!');
  lines.push('');
  lines.push('3. **Compile**');
  lines.push('   - Click the big green **"Recompile"** button at the top.');
  lines.push('   - The PDF preview will appear on the right panel.');
  lines.push('   - If there are errors, check the **"Logs and output files"** panel at the bottom.');
  lines.push('');
  lines.push('4. **Set the compiler**');
  lines.push('   - Click the **Menu** button (top-left) → **Settings**.');
  lines.push('   - Set the compiler to **pdfLaTeX** (default), **XeLaTeX**, or **LuaLaTeX** as needed.');
  lines.push('   - Turn on **"Shell escape"** only if instructed by an error message.');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Local Compilation with pdfLaTeX ──
  lines.push('## Local Compilation with pdfLaTeX');
  lines.push('');
  lines.push('### Prerequisites');
  lines.push('');
  lines.push('Install a TeX distribution for your operating system:');
  lines.push('');
  lines.push('| OS | Distribution | Link |');
  lines.push('|----|-------------|------|');
  lines.push('| **Windows** | MiKTeX or TeX Live | [miktex.org](https://miktex.org) / [tug.org/texlive](https://tug.org/texlive) |');
  lines.push('| **macOS** | MacTeX (TeX Live) | [tug.org/mactex](https://tug.org/mactex) |');
  lines.push('| **Linux** | TeX Live | `sudo apt install texlive-full` (Debian/Ubuntu) |');
  lines.push('');
  lines.push('### Compilation Sequence');
  lines.push('');

  if (hasBib) {
    lines.push(`#### With BibTeX (your document has ${data.references.length} reference(s)):`);
    lines.push('');
    lines.push('```bash');
    lines.push('# Step 1: First pass — resolves labels and writes .aux file');
    lines.push('pdflatex main.tex');
    lines.push('');
    lines.push('# Step 2: Generate bibliography from .aux + .bib');
    lines.push(bibTool + ' main');
    lines.push('');
    lines.push('# Step 3: Second pass — incorporates bibliography');
    lines.push('pdflatex main.tex');
    lines.push('');
    lines.push('# Step 4: Third pass — resolves all cross-references (?? → numbers)');
    lines.push('pdflatex main.tex');
    lines.push('```');
    lines.push('');
    lines.push('> **Why four passes?**');
    lines.push('> - Pass 1 writes the `.aux` file with citation keys');
    lines.push(`> - ${bibToolLabel} reads \`.aux\` + \`.bib\` and writes \`.bbl\``);
    lines.push('> - Pass 2 includes the generated bibliography');
    lines.push('> - Pass 3 resolves forward references (Chapter 2 → see Section 3.1)');
  } else {
    lines.push('#### Without BibTeX (no references detected):');
    lines.push('');
    lines.push('```bash');
    lines.push('# Two passes to resolve cross-references');
    lines.push('pdflatex main.tex');
    lines.push('pdflatex main.tex');
    lines.push('```');
  }

  lines.push('');
  lines.push('### Clean Build');
  lines.push('');
  lines.push('If you encounter stale cache issues, delete auxiliary files first:');
  lines.push('');
  lines.push('```bash');
  lines.push('# Remove all auxiliary files');
  lines.push('rm -f *.aux *.log *.out *.toc *.lof *.lot *.bbl *.blg *.fdb_latexmk *.fls *.synctex.gz');
  lines.push('');
  lines.push('# Then recompile from scratch');
  lines.push(hasBib
    ? `pdflatex main.tex && ${bibTool} main && pdflatex main.tex && pdflatex main.tex`
    : 'pdflatex main.tex && pdflatex main.tex');
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── XeLaTeX Alternative ──
  lines.push('## XeLaTeX Alternative');
  lines.push('');
  lines.push('XeLaTeX natively supports **UTF-8** and system fonts. Use it if you need:');
  lines.push('- Non-Latin scripts (Chinese, Arabic, Cyrillic, etc.)');
  lines.push('- Custom TrueType/OpenType fonts');
  lines.push('- Modern font features (ligatures, small caps, etc.)');
  lines.push('');
  lines.push('### Setup');
  lines.push('');
  lines.push('Remove `inputenc` and `fontenc` from the preamble (XeLaTeX doesn\'t need them).');
  lines.push('Add instead:');
  lines.push('```latex');
  lines.push('\\usepackage{fontspec}');
  lines.push('\\setmainfont{Your Font Name}');
  lines.push('```');
  lines.push('');
  lines.push('### Compile');
  lines.push('');
  lines.push('```bash');
  if (hasBib) {
    lines.push(`xelatex main.tex\n${bibTool} main\nxelatex main.tex\nxelatex main.tex`);
  } else {
    lines.push('xelatex main.tex\nxelatex main.tex');
  }
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── LuaLaTeX Alternative ──
  lines.push('## LuaLaTeX Alternative');
  lines.push('');
  lines.push('LuaLaTeX is the most powerful engine. It supports everything XeLaTeX does,');
  lines.push('plus Lua scripting for advanced customization.');
  lines.push('');
  lines.push('### Compile');
  lines.push('');
  lines.push('```bash');
  if (hasBib) {
    lines.push(`lualatex main.tex\n${bibTool} main\nlualatex main.tex\nlualatex main.tex`);
  } else {
    lines.push('lualatex main.tex\nlualatex main.tex');
  }
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Package Dependencies ──
  lines.push('## Package Dependencies');
  lines.push('');
  lines.push('### Core Packages (required by all templates)');
  lines.push('');
  lines.push('| Package | Purpose | TeX Live |');
  lines.push('|---------|---------|----------|');
  lines.push('| `inputenc` | UTF-8 input encoding | `texlive-latex-recommended` |');
  lines.push('| `fontenc` | Font encoding (T1) | `texlive-latex-recommended` |');
  lines.push('| `lmodern` | Latin Modern fonts | `texlive-fonts-recommended` |');
  lines.push('| `geometry` | Page layout and margins | `texlive-latex-recommended` |');
  lines.push('| `graphicx` | Image inclusion | `texlive-latex-recommended` |');
  lines.push('| `amsmath` | Math environments | `texlive-latex-recommended` |');
  lines.push('| `amssymb` | Math symbols | `texlive-latex-recommended` |');
  lines.push('| `booktabs` | Professional tables | `texlive-latex-recommended` |');
  lines.push('| `hyperref` | Hyperlinks and PDF metadata | `texlive-latex-recommended` |');
  lines.push('| `cleveref` | Smart cross-referencing | `texlive-latex-extra` |');
  lines.push('| `natbib` / `biblatex` | Citation management | `texlive-bibtex-extra` |');
  lines.push('| `setspace` | Line spacing control | `texlive-latex-recommended` |');
  lines.push('| `fancyhdr` | Headers and footers | `texlive-latex-recommended` |');
  lines.push('| `caption` | Caption formatting | `texlive-latex-recommended` |');
  lines.push('| `microtype` | Microtypographic improvements | `texlive-latex-recommended` |');
  lines.push('| `enumitem` | List customization | `texlive-latex-recommended` |');
  lines.push('');
  lines.push('### Optional Packages');
  lines.push('');

  if (data.options.includeListings) {
    lines.push('| `listings` | Code listings | `texlive-latex-extra` |');
    lines.push('| `xcolor` | Color support | `texlive-latex-recommended` |');
    lines.push('');
  }

  if (templateId === 'phd') {
    lines.push('| `nomencl` | Nomenclature | `texlive-science` |');
    lines.push('| `glossaries` | Glossary/acronym | `texlive-latex-extra` |');
    lines.push('| `amsthm` | Theorem environments | `texlive-latex-recommended` |');
    lines.push('| `mathtools` | Extended math tools | `texlive-latex-extra` |');
    lines.push('');
  } else if (templateId === 'master') {
    lines.push('| `amsthm` | Theorem environments | `texlive-latex-recommended` |');
    lines.push('');
  }

  lines.push('### Installing Missing Packages');
  lines.push('');
  lines.push('```bash');
  lines.push('# TeX Live (Linux)');
  lines.push('sudo tlmgr install <package-name>');
  lines.push('');
  lines.push('# MiKTeX (Windows)');
  lines.push('# Packages install automatically on first use, or use the MiKTeX Console.');
  lines.push('');
  lines.push('# MacTeX');
  lines.push('# All packages are included in the full installation.');
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Common Errors & Solutions ──
  lines.push('## Common Errors & Solutions');
  lines.push('');

  lines.push('### 1. "Undefined control sequence"');
  lines.push('');
  lines.push('**Cause:** A LaTeX command is misspelled or a required package is missing.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Check the spelling of the command.');
  lines.push('- Ensure the required package is loaded with `\\usepackage{...}`.');
  lines.push('- Run `kpsewhich <package>.sty` to check if a package is installed.');
  lines.push('');

  lines.push('### 2. "Missing $ inserted" or "Math mode error"');
  lines.push('');
  lines.push('**Cause:** Math symbols (\\alpha, \\beta, _, ^) used outside math mode.');
  lines.push('');
  lines.push('**Fix:** Wrap math content in `$...$` (inline) or `\\[...\\]` / `\\begin{equation}\\end{equation}` (display).');
  lines.push('');

  lines.push('### 3. "File not found" for images');
  lines.push('');
  lines.push('**Cause:** The image file path is incorrect or the file is missing.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Ensure image files are in the `figures/` directory.');
  lines.push('- Check the path in `\\includegraphics{...}` matches the filename exactly.');
  lines.push('- Supported formats: `.pdf`, `.png`, `.jpg`, `.eps`.');
  lines.push('');

  lines.push('### 4. "Undefined references" (?? or ??)');
  lines.push('');
  lines.push('**Cause:** Cross-references (`\\ref`, `\\cref`, `\\cite`) point to undefined labels.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Compile **twice** (or follow the full 4-pass sequence for BibTeX).');
  lines.push('- Verify that `\\label{...}` exists for every `\\ref{...}`.');
  lines.push('- Verify that citation keys in `\\cite{...}` match keys in `references.bib`.');
  lines.push('');

  lines.push('### 5. "Bibliography not found" or empty bibliography');
  lines.push('');
  lines.push('**Cause:** BibTeX can\'t find or process the `.bib` file.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Ensure `references.bib` is in the **same directory** as `main.tex`.');
  lines.push('- Check that citation keys in `\\cite{...}` exactly match keys in `references.bib` (case-sensitive).');
  lines.push('- Run the full compile sequence: `pdflatex → bibtex → pdflatex → pdflatex`.');
  lines.push('');

  lines.push('### 6. "Encoding error" or garbled characters');
  lines.push('');
  lines.push('**Cause:** Non-ASCII characters without proper encoding setup.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- **pdfLaTeX:** Ensure `\\usepackage[utf8]{inputenc}` is in the preamble.');
  lines.push('- **XeLaTeX/LuaLaTeX:** Use `\\usepackage{fontspec}` instead (no inputenc needed).');
  lines.push('- Replace smart quotes (" " \' \') with LaTeX equivalents (`` \'\' ` \').');
  lines.push('- Replace en-dashes (–) with `--` and em-dashes (—) with `---`.');
  lines.push('');

  lines.push('### 7. "Too many unprocessed floats"');
  lines.push('');
  lines.push('**Cause:** Too many figures/tables waiting to be placed.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Add `\\usepackage[morefloats]{stfloats}` to the preamble.');
  lines.push('- Or place `[htbp]` modifiers on float environments.');
  lines.push('- Or add `\\clearpage` to force float placement.');
  lines.push('');

  lines.push('### 8. "Overfull \\hbox" warnings');
  lines.push('');
  lines.push('**Cause:** A line is too wide for the page margins.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- These are usually cosmetic. Check the PDF output.');
  lines.push('- Fix hyphenation by adding `\\hyphenation{word-to-hy-phen-ate}`.');
  lines.push('- Adjust wording or font size if persistent.');
  lines.push('');

  lines.push('### 9. Missing package errors (MiKTeX)');
  lines.push('');
  lines.push('**Cause:** Package not installed.');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- MiKTeX should auto-install. If not, open **MiKTeX Console** → install the package.');
  lines.push('- Or enable auto-install: MiKTeX Console → Settings → "Always install missing packages".');
  lines.push('');

  lines.push('### 10. "Permission denied" or "write error"');
  lines.push('');
  lines.push('**Cause:** Output files are locked by another program (PDF viewer, editor).');
  lines.push('');
  lines.push('**Fix:**');
  lines.push('- Close the PDF in your viewer before recompiling.');
  lines.push('- Use a viewer that auto-reloads (SumatraPDF on Windows, Skim on macOS).');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Troubleshooting Checklist ──
  lines.push('## Troubleshooting Checklist');
  lines.push('');
  lines.push('Run through this list if compilation fails:');
  lines.push('');
  lines.push('- [ ] All files (`main.tex`, `references.bib`) are in the **same directory**');
  lines.push('- [ ] You are using the correct compiler (pdfLaTeX / XeLaTeX / LuaLaTeX)');
  lines.push('- [ ] You have run **enough compilation passes** (at least 2, or 4 with BibTeX)');
  lines.push('- [ ] All `\\begin{...}` have matching `\\end{...}`');
  lines.push('- [ ] All `{` have matching `}`');
  lines.push('- [ ] All citation keys in `\\cite{...}` exist in `references.bib`');
  lines.push('- [ ] All `\\label{...}` referenced by `\\ref{...}` exist');
  lines.push('- [ ] Image files are in the correct path (default: `figures/`)');
  lines.push('- [ ] No special characters outside of math mode (`_`, `^`, `&`, `#`)');
  lines.push('- [ ] `hyperref` is loaded **last** (or second-to-last before `cleveref`)');
  lines.push('- [ ] The `.aux` file is not stale (delete and recompile if unsure)');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [ThesisForge](https://thesisforge.vercel.app) — ${generatedDate}*`);

  return lines.join('\n');
}

// ============================================================
// Figures Directory Placeholder
// ============================================================

const FIGURES_PLACEHOLDER = `This directory should contain your figures and images.
Supported formats: .pdf, .png, .jpg, .eps
Reference them in your thesis using: \\includegraphics[width=\\textwidth]{figures/your-image}

Tips:
- Use vector formats (.pdf, .eps) for diagrams and plots
- Use .png for screenshots (minimum 300 DPI for print)
- Use .jpg for photographs (minimum 300 DPI for print)
- Keep filenames simple: no spaces, no special characters
- Good examples: fig-methodology.pdf, results-chart.png, photo-setup.jpg
- Avoid: My Figure (Final) v2.png
`;

// ============================================================
// BibLaTeX Mode Support
// ============================================================

const BIBLATEX_STYLES: Record<CitationStyle, string> = {
  ieee: 'ieee',
  apa: 'apa',
  vancouver: 'vancouver',
  chicago: 'chicago-authordate',
  harvard: 'authoryear',
};

/**
 * Generate BibLaTeX block as an alternative to natbib.
 * Returns null if BibLaTeX mode is not applicable.
 */
export function generateBibLaTeXBlock(data: ThesisData): string | null {
  const style = BIBLATEX_STYLES[data.options.citationStyle] || 'authoryear';

  const lines: string[] = [];
  lines.push('% BibLaTeX configuration (alternative to natbib)');
  lines.push(`\\usepackage[backend=biber,style=${style}]{biblatex}`);
  lines.push(`\\addbibresource{references.bib}`);
  lines.push('');

  // Add some useful BibLaTeX settings
  lines.push('% BibLaTeX fine-tuning');
  lines.push('\\DeclareFieldFormat{labeltitle}{\\textit{#1}}');
  lines.push('\\DeclareFieldFormat{title}{\\textit{#1}}');
  lines.push('\\DeclareFieldFormat[article]{pages}{#1}');
  lines.push('\\DeclareFieldFormat[inbook]{pages}{#1}');

  if (data.options.citationStyle === 'ieee') {
    lines.push('');
    lines.push('% IEEE-style numeric citations');
    lines.push('\\DeclareSourcemap{');
    lines.push('  \\maps[datatype=bibtex]{');
    lines.push('    \\map{');
    lines.push('      \\pertype{inproceedings}');
    lines.push('      \\step[fieldset=booktitle, fieldvalue={\\bibstring{inproceedings}}]');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
  }

  return lines.join('\n');
}

// ============================================================
// Storage Usage Estimator
// ============================================================

/**
 * Estimate the storage usage (in KB) of the current thesis draft.
 * Includes estimated sizes for .tex, .bib, figures placeholder, README, and COMPILE.md.
 */
export function estimateStorageUsageKB(data: ThesisData): number {
  let totalBytes = 0;

  // Estimate .tex file size: ~2 bytes per character (UTF-8), plus template overhead
  const metadataValues = Object.values(data.metadata);
  const metadataChars = metadataValues.reduce((sum: number, val) => sum + String(val).length, 0);
  const abstractChars = (data.abstract || '').length;
  const keywordsChars = data.keywords.reduce((sum, kw) => sum + kw.length, 0);
  const chaptersChars = data.chapters.reduce((sum, ch) => {
    const contentLen = (ch.content || '').length;
    const subSectionsLen = ch.subSections.reduce((s, ss) => s + (ss.content || '').length + ss.title.length, 0);
    return sum + ch.title.length + contentLen + subSectionsLen;
  }, 0);
  const appendicesChars = data.appendices.reduce((sum, ap) => sum + ap.title.length + (ap.content || '').length, 0);

  // LaTeX template overhead (~3KB for preamble + structure)
  const templateOverhead = 3000;
  const contentBytes = (metadataChars + abstractChars + keywordsChars + chaptersChars + appendicesChars) * 2;
  totalBytes += templateOverhead + contentBytes;

  // Estimate .bib file size
  const bibOverheadPerRef = 300; // Average bytes per BibTeX entry
  totalBytes += data.references.length * bibOverheadPerRef;

  // README.md
  totalBytes += 1500;

  // COMPILE.md
  totalBytes += 8000;

  // Figures placeholder
  totalBytes += 500;

  // Convert to KB with 1 decimal
  return Math.round((totalBytes / 1024) * 10) / 10;
}

// ============================================================
// Pre-Export Checklist Builder
// ============================================================

/**
 * Category mapping from contract check IDs to ChecklistItem categories.
 */
function checkIdToCategory(id: string): ChecklistItem['category'] {
  if (id.startsWith('C')) return 'compilability';
  if (id.startsWith('P')) return 'packages';
  if (id.startsWith('S')) return 'structure';
  if (id.startsWith('B')) return 'bibliography';
  if (id.startsWith('M')) return 'metadata';
  if (id.startsWith('Q') || id.startsWith('A')) return 'quality';
  return 'compilability';
}

/**
 * Build a pre-export checklist from contract checks, intelligence report,
 * and thesis data.
 */
function buildChecklist(
  tex: string,
  bib: string,
  data: ThesisData,
  intelligence: IntelligenceReport | undefined,
): ChecklistItem[] {
  const items: ChecklistItem[] = [];

  // 1. Run all contract checks and convert to checklist items
  const fullReport = getFullContractReport(tex, bib, data);
  for (const result of fullReport) {
    items.push({
      id: result.id,
      category: checkIdToCategory(result.id),
      passed: result.passed,
      message: result.message,
      severity: result.severity as ChecklistItem['severity'],
    });
  }

  // 2. Add intelligence-derived checks
  if (intelligence) {
    // Cross-reference checks
    if (intelligence.crossRefs.undefined.length > 0) {
      const undefinedLabels = intelligence.crossRefs.undefined.map(u => u.ref).join(', ');
      items.push({
        id: 'INT-CREF',
        category: 'structure',
        passed: false,
        message: `Undefined cross-references: ${undefinedLabels}`,
        severity: 'warning',
      });
    } else if (intelligence.crossRefs.totalRefs > 0) {
      items.push({
        id: 'INT-CREF',
        category: 'structure',
        passed: true,
        message: 'All cross-references resolved',
        severity: 'info',
      });
    }

    // Orphan section checks
    for (const orphan of intelligence.orphans) {
      items.push({
        id: `INT-ORPHAN-${orphan.chapterId.slice(0, 8)}`,
        category: 'quality',
        passed: false,
        message: orphan.message,
        severity: 'warning',
      });
    }

    // Citation density checks
    for (const cd of intelligence.citationDensity) {
      if (cd.status === 'no-citations') {
        items.push({
          id: `INT-CITE-${cd.chapterId.slice(0, 8)}`,
          category: 'bibliography',
          passed: false,
          message: `"${cd.chapterTitle}" has no citations (${cd.wordCount} words)`,
          severity: 'warning',
        });
      } else if (cd.status === 'over-cited') {
        items.push({
          id: `INT-CITE-${cd.chapterId.slice(0, 8)}`,
          category: 'bibliography',
          passed: false,
          message: `"${cd.chapterTitle}" may be over-cited (${cd.density} citations/100 words)`,
          severity: 'info',
        });
      }
    }

    // Abstract quality
    if (intelligence.abstractAudit) {
      const audit = intelligence.abstractAudit;
      if (audit.wordCount > 0 && audit.passCount < 3) {
        items.push({
          id: 'INT-ABS',
          category: 'quality',
          passed: false,
          message: `Abstract quality: ${audit.passCount}/5 elements present. ${audit.issues.slice(0, 2).join(' ')}`,
          severity: 'warning',
        });
      } else if (audit.wordCount > 0 && audit.passCount >= 3) {
        items.push({
          id: 'INT-ABS',
          category: 'quality',
          passed: true,
          message: `Abstract quality: ${audit.passCount}/5 elements present`,
          severity: 'info',
        });
      }
    }

    // Chapter word count checks
    for (const wc of intelligence.chapterWordCounts) {
      if (wc.status === 'empty') {
        items.push({
          id: `INT-WC-${wc.chapterId.slice(0, 8)}`,
          category: 'quality',
          passed: false,
          message: `"${wc.chapterTitle}" is empty — no content written`,
          severity: 'error',
        });
      } else if (wc.status === 'thin') {
        items.push({
          id: `INT-WC-${wc.chapterId.slice(0, 8)}`,
          category: 'quality',
          passed: false,
          message: `"${wc.chapterTitle}" is thin (${wc.wordCount} words) — consider expanding`,
          severity: 'warning',
        });
      }
    }

    // Structure balance warnings
    for (const warning of intelligence.structureBalance.imbalanceWarnings) {
      items.push({
        id: `INT-BAL-${items.length}`,
        category: 'structure',
        passed: false,
        message: warning,
        severity: 'warning',
      });
    }
  }

  // 3. Add basic content completeness checks
  if (!data.metadata.title.trim()) {
    items.push({
      id: 'META-TITLE',
      category: 'metadata',
      passed: false,
      message: 'Thesis title is empty',
      severity: 'error',
    });
  }

  if (!data.metadata.author.trim()) {
    items.push({
      id: 'META-AUTHOR',
      category: 'metadata',
      passed: false,
      message: 'Author name is empty',
      severity: 'error',
    });
  }

  if (!data.abstract.trim()) {
    items.push({
      id: 'META-ABSTRACT',
      category: 'metadata',
      passed: false,
      message: 'Abstract is empty',
      severity: 'warning',
    });
  }

  if (data.keywords.length === 0) {
    items.push({
      id: 'META-KEYWORDS',
      category: 'metadata',
      passed: false,
      message: 'No keywords defined',
      severity: 'info',
    });
  }

  const totalWords = data.chapters.reduce((sum, ch) => sum + countWords(ch.content || ''), 0);
  if (totalWords < 100) {
    items.push({
      id: 'QUAL-LENGTH',
      category: 'quality',
      passed: false,
      message: `Very low word count (${totalWords} words). Most chapters appear empty.`,
      severity: 'warning',
    });
  }

  return items;
}

/**
 * Compute a health score (0-100) from checklist items.
 * Error failures are weighted heavily, warnings moderately, info lightly.
 */
function computeHealthScore(checklist: ChecklistItem[]): number {
  if (checklist.length === 0) return 100;

  let score = 100;
  for (const item of checklist) {
    if (item.passed) continue;
    switch (item.severity) {
      case 'error':
        score -= 15;
        break;
      case 'warning':
        score -= 5;
        break;
      case 'info':
        score -= 1;
        break;
    }
  }

  return Math.max(0, Math.min(100, score));
}

// ============================================================
// Export Pipeline
// ============================================================

/**
 * Export thesis as a ZIP file.
 * Runs entirely client-side. No server required.
 *
 * v3: Runs expanded 30-check contract + intelligence analysis.
 * Returns results for UI display.
 *
 * v3.1: Adds checklist, healthScore, COMPILE.md, figures placeholder.
 */
export async function exportThesis(
  data: ThesisData,
  templateId: ThesisType
): Promise<ExportResult> {
  try {
    const tex = generateLatex(data);

    // Use enhanced BibTeX generation from bib.ts
    const bib = generateBibFromThesisReferences(data.references);

    const readme = generateReadme(data, templateId);
    const compileMd = generateCompileMd(data, templateId);

    // Run expanded 30-check contract
    const contractErrors = assertLatexContract(tex, bib, data, 'warning');
    const summary = contractSummary(tex, bib, data);

    // Run intelligence analysis
    const intelligence = await runIntelligence(data);

    // Build pre-export checklist
    const checklist = buildChecklist(tex, bib, data, intelligence);
    const healthScore = computeHealthScore(checklist);

    // Block export on errors only (warnings and info don't block)
    // Severity filtering: only C01-C06 are errors, C07+ are warnings
    const hasErrors = contractErrors.some(e => {
      return e.code === 'C01' || e.code === 'C02' || e.code === 'C03' ||
             e.code === 'C04' || e.code === 'C05' || e.code === 'C06';
    });

    if (hasErrors) {
      return { errors: contractErrors, contractSummary: summary, intelligence, checklist, healthScore };
    }

    const zip = new JSZip();
    const folderName = sanitizeFilename(data.metadata.title) || 'thesis';
    const folder = zip.folder(folderName);

    if (!folder) throw new Error('Failed to create ZIP folder');

    folder.file('main.tex', tex);
    folder.file('references.bib', bib);
    folder.file('README.md', readme);
    folder.file('COMPILE.md', compileMd);

    // Add figures folder placeholder with instructions
    const figuresFolder = folder.folder('figures');
    if (figuresFolder) {
      figuresFolder.file('PLACEHOLDER.txt', FIGURES_PLACEHOLDER);
    }

    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    triggerDownload(blob, `${folderName}.zip`);

    return {
      errors: contractErrors.length > 0 ? contractErrors : undefined,
      contractSummary: summary,
      intelligence,
      checklist,
      healthScore,
    };
  } catch (err) {
    throw err;
  }
}

/**
 * Export just the .tex file.
 */
export async function exportTexOnly(data: ThesisData): Promise<void> {
  const tex = generateLatex(data);
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([tex], { type: 'text/x-tex' });
  triggerDownload(blob, `${filename}.tex`);
}

/**
 * Export just the .bib file.
 */
export async function exportBibOnly(data: ThesisData): Promise<void> {
  const bib = generateBibFromThesisReferences(data.references);
  const filename = sanitizeFilename(data.metadata.title) || 'thesis';
  const blob = new Blob([bib], { type: 'text/plain' });
  triggerDownload(blob, `${filename}_references.bib`);
}

/**
 * Run contract checks without exporting.
 * Used by the UI to show lint results.
 */
export async function runContractChecks(data: ThesisData): Promise<ExportResult> {
  const tex = generateLatex(data);
  const bib = generateBibFromThesisReferences(data.references);
  const contractErrors = assertLatexContract(tex, bib, data, 'info');
  const summary = contractSummary(tex, bib, data);
  const intelligence = await runIntelligence(data);

  // Build checklist and health score
  const checklist = buildChecklist(tex, bib, data, intelligence);
  const healthScore = computeHealthScore(checklist);

  return {
    errors: contractErrors.length > 0 ? contractErrors : undefined,
    contractSummary: summary,
    intelligence,
    checklist,
    healthScore,
  };
}

/**
 * Trigger a file download in the browser.
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
